/* A lexical scanner generated by flex */
/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 * $FreeBSD: src/usr.bin/lex/flex.skl,v 1.4 1999/10/27 07:56:44 obrien Exp $
 */
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#include <stdio.h>
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#include <stdlib.h>
#include <unistd.h>
/* Use prototypes in function declarations. */
#define YY_USE_PROTOS
/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST
#else  /* ! __cplusplus */
#if __STDC__
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif /* __STDC__ */
#endif /* ! __cplusplus */
#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif
#ifdef YY_USE_CONST
#define GUC_yyconst const
#else
#define GUC_yyconst
#endif
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
/* Returned upon end-of-file. */
#define YY_NULL 0
/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN GUC_yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((GUC_yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE GUC_yyrestart( GUC_yyin )
#define YY_END_OF_BUFFER_CHAR 0
/* Size of default input buffer. */
#define YY_BUF_SIZE 16384
typedef struct GUC_yy_buffer_state *YY_BUFFER_STATE;
extern int GUC_yyleng;
extern FILE *GUC_yyin, *GUC_yyout;
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *     if ( condition_holds )
 *         GUC_yyless( 5 );
 *     else
 *         do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the GUC_yyless() call.
 */
/* Return all but the first 'n' matched characters back to the input stream. */
#define GUC_yyless(n) \
       do \
             { \
             /* Undo effects of setting up GUC_yytext. */ \
             *GUC_yy_cp = GUC_yy_hold_char; \
             YY_RESTORE_YY_MORE_OFFSET \
             GUC_yy_c_buf_p = GUC_yy_cp = GUC_yy_bp + n - YY_MORE_ADJ; \
             YY_DO_BEFORE_ACTION; /* set up GUC_yytext again */ \
             } \
       while ( 0 )
#define unput(c) GUC_yyunput( c, GUC_yytext_ptr )
/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int GUC_yy_size_t;
struct GUC_yy_buffer_state {
       FILE *GUC_yy_input_file;
       char *GUC_yy_ch_buf;   /* input buffer */
       char *GUC_yy_buf_pos;         /* current position in input buffer */
       /* Size of input buffer in bytes, not including room for EOB
        * characters.
        */
       GUC_yy_size_t GUC_yy_buf_size;
       /* Number of characters read into GUC_yy_ch_buf, not including EOB
        * characters.
        */
       int GUC_yy_n_chars;
       /* Whether we "own" the buffer - i.e., we know we created it,
        * and can realloc() it to grow it, and should free() it to
        * delete it.
        */
       int GUC_yy_is_our_buffer;
       /* Whether this is an "interactive" input source; if so, and
        * if we're using stdio for input, then we want to use getc()
        * instead of fread(), to make sure we stop fetching input after
        * each newline.
        */
       int GUC_yy_is_interactive;
       /* Whether we're considered to be at the beginning of a line.
        * If so, '^' rules will be active on the next match, otherwise
        * not.
        */
       int GUC_yy_at_bol;
       /* Whether to try to fill the input buffer when we reach the
        * end of it.
        */
       int GUC_yy_fill_buffer;
       int GUC_yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
       /* When an EOF's been seen but there's still some text to process
        * then we mark the buffer as YY_EOF_PENDING, to indicate that we
        * shouldn't try reading from the input source any more.  We might
        * still have a bunch of tokens to match, though, because of
        * possible backing-up.
        *
        * When we actually see the EOF, we change the status to "new"
        * (via GUC_yyrestart()), so that the user can continue scanning by
        * just pointing GUC_yyin at a new input file.
        */
#define YY_BUFFER_EOF_PENDING 2
       };
static YY_BUFFER_STATE GUC_yy_current_buffer = 0;
/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER GUC_yy_current_buffer
/* GUC_yy_hold_char holds the character lost when GUC_yytext is formed. */
static char GUC_yy_hold_char;
static int GUC_yy_n_chars;         /* number of characters read into GUC_yy_ch_buf */
int GUC_yyleng;
/* Points to current character in buffer. */
static char *GUC_yy_c_buf_p = (char *) 0;
static int GUC_yy_init = 1;       /* whether we need to initialize */
static int GUC_yy_start = 0;   /* start state number */
/* Flag which is used to allow GUC_yywrap()'s to do buffer switches
 * instead of setting up a fresh GUC_yyin.  A bit of a hack ...
 */
static int GUC_yy_did_buffer_switch_on_eof;
void GUC_yyrestart YY_PROTO(( FILE *input_file ));
void GUC_yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void GUC_yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE GUC_yy_create_buffer YY_PROTO(( FILE *file, int size ));
void GUC_yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void GUC_yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void GUC_yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER GUC_yy_flush_buffer( GUC_yy_current_buffer )
YY_BUFFER_STATE GUC_yy_scan_buffer YY_PROTO(( char *base, GUC_yy_size_t size ));
YY_BUFFER_STATE GUC_yy_scan_string YY_PROTO(( GUC_yyconst char *GUC_yy_str ));
YY_BUFFER_STATE GUC_yy_scan_bytes YY_PROTO(( GUC_yyconst char *bytes, int len ));
static void *GUC_yy_flex_alloc YY_PROTO(( GUC_yy_size_t ));
static void *GUC_yy_flex_realloc YY_PROTO(( void *, GUC_yy_size_t ));
static void GUC_yy_flex_free YY_PROTO(( void * ));
#define GUC_yy_new_buffer GUC_yy_create_buffer
#define GUC_yy_set_interactive(is_interactive) \
       { \
       if ( ! GUC_yy_current_buffer ) \
             GUC_yy_current_buffer = GUC_yy_create_buffer( GUC_yyin, YY_BUF_SIZE ); \
       GUC_yy_current_buffer->GUC_yy_is_interactive = is_interactive; \
       }
#define GUC_yy_set_bol(at_bol) \
       { \
       if ( ! GUC_yy_current_buffer ) \
             GUC_yy_current_buffer = GUC_yy_create_buffer( GUC_yyin, YY_BUF_SIZE ); \
       GUC_yy_current_buffer->GUC_yy_at_bol = at_bol; \
       }
#define YY_AT_BOL() (GUC_yy_current_buffer->GUC_yy_at_bol)
typedef unsigned char YY_CHAR;
FILE *GUC_yyin = (FILE *) 0, *GUC_yyout = (FILE *) 0;
typedef int GUC_yy_state_type;
extern char *GUC_yytext;
#define GUC_yytext_ptr GUC_yytext
static GUC_yy_state_type GUC_yy_get_previous_state YY_PROTO(( void ));
static GUC_yy_state_type GUC_yy_try_NUL_trans YY_PROTO(( GUC_yy_state_type current_state ));
static int GUC_yy_get_next_buffer YY_PROTO(( void ));
static void GUC_yy_fatal_error YY_PROTO(( GUC_yyconst char msg[] ));
/* Done after the current pattern has been matched and before the
 * corresponding action - sets up GUC_yytext.
 */
#define YY_DO_BEFORE_ACTION \
       GUC_yytext_ptr = GUC_yy_bp; \
       GUC_yyleng = (int) (GUC_yy_cp - GUC_yy_bp); \
       GUC_yy_hold_char = *GUC_yy_cp; \
       *GUC_yy_cp = '\0'; \
       GUC_yy_c_buf_p = GUC_yy_cp;
#define YY_NUM_RULES 11
#define YY_END_OF_BUFFER 12
static GUC_yyconst short int GUC_yy_accept[38] =
    {   0,
        0,    0,   12,   10,    2,    1,   10,   10,   10,    8,
        7,    7,    9,    4,    2,    0,    3,    0,    5,    0,
        8,    7,    7,    8,    0,    0,    6,    4,    4,    0,
        5,    0,    0,    8,    7,    6,    0
    } ;
static GUC_yyconst int GUC_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    5,    1,
        1,    1,    6,    1,    7,    8,    9,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    9,    1,    1,
       12,    1,    1,    1,   13,   13,   13,   13,   14,   13,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        1,   16,    1,    1,   17,    1,   13,   13,   13,   13,
       14,   13,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   18,
       15,   15,    1,    1,    1,    1,    1,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15
    } ;
static GUC_yyconst int GUC_yy_meta[19] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    3,    4,
        4,    1,    5,    4,    3,    1,    3,    3
    } ;
static GUC_yyconst short int GUC_yy_base[45] =
    {   0,
        0,    0,   61,   86,   58,   86,   55,   14,   23,   43,
       10,   46,   86,   28,   47,   40,   86,   16,   86,   22,
       28,    0,    0,    0,   40,    0,   24,   45,    0,   24,
       39,   43,   12,   14,    0,   22,   86,   62,   67,   22,
       70,   75,   77,   80
    } ;
static GUC_yyconst short int GUC_yy_def[45] =
    {   0,
       37,    1,   37,   37,   37,   37,   38,   39,   37,   40,
        9,    9,   37,   41,   37,   38,   37,   39,   37,   42,
       40,   11,   12,   21,   37,   43,   44,   41,   28,   39,
       39,   42,   37,   37,   43,   44,    0,   37,   37,   37,
       37,   37,   37,   37
    } ;
static GUC_yyconst short int GUC_yy_nxt[105] =
    {   0,
        4,    5,    6,    7,    8,    9,    9,   10,    4,   11,
       12,   13,   14,   14,   14,    4,   14,   14,   19,   23,
       19,   34,   34,   34,   34,   24,   31,   26,   19,   20,
       21,   20,   22,   23,   27,   27,   27,   32,   36,   20,
       36,   25,   17,   19,   29,   33,   33,   31,   15,   34,
       34,   27,   27,   27,   20,   23,   25,   17,   32,   15,
       37,   29,   16,   16,   16,   16,   16,   18,   37,   18,
       18,   18,   28,   28,   28,   30,   37,   30,   30,   30,
       35,   35,   27,   27,   27,    3,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37
    } ;
static GUC_yyconst short int GUC_yy_chk[105] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,   11,
       18,   33,   33,   34,   34,   40,   20,   11,   30,    8,
        9,   18,    9,    9,   14,   14,   14,   20,   36,   30,
       27,   21,   16,   31,   14,   25,   25,   32,   15,   25,
       25,   28,   28,   28,   31,   12,   10,    7,   32,    5,
        3,   28,   38,   38,   38,   38,   38,   39,    0,   39,
       39,   39,   41,   41,   41,   42,    0,   42,   42,   42,
       43,   43,   44,   44,   44,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37
    } ;
static GUC_yy_state_type GUC_yy_last_accepting_state;
static char *GUC_yy_last_accepting_cpos;
/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define GUC_yymore() GUC_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *GUC_yytext;
#define INITIAL 0
/* -*-pgsql-c-*- */
/*
 * Scanner for the configuration file
 *
 * Copyright 2000 by PostgreSQL Global Development Group
 *
 * $Header: /cvsroot/pgsql/src/backend/utils/misc/guc-file.l,v 1.9 2001/08/06 13:45:15 petere Exp $
 */
#include "postgres.h"
#include <string.h>
#include <stdarg.h>
#include <sys/stat.h>
#include <unistd.h>
#include <errno.h>
#include <ctype.h>
#include "miscadmin.h"
#include "storage/fd.h"
#include "utils/elog.h"
#include "utils/guc.h"
#define CONFIG_FILENAME "postgresql.conf"
static unsigned ConfigFileLineno;
enum {
       GUC_ID = 1,
       GUC_STRING = 2,
       GUC_INTEGER = 3,
       GUC_REAL = 4,
       GUC_EQUALS = 5,
       GUC_UNQUOTED_STRING = 6,
       GUC_EOL = 99,
       GUC_ERROR = 100
};
#if defined(GUC_yywrap)
#undef GUC_yywrap
#endif /* GUC_yywrap */
#define YY_USER_INIT (ConfigFileLineno = 1)
#define YY_NO_UNPUT
/* prototype, so compiler is happy with our high warnings setting */
int GUC_yylex(void);
char *GUC_scanstr(char *);
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */
#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int GUC_yywrap YY_PROTO(( void ));
#else
extern int GUC_yywrap YY_PROTO(( void ));
#endif
#endif
#ifndef YY_NO_UNPUT
static void GUC_yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif
#ifndef GUC_yytext_ptr
static void GUC_yy_flex_strncpy YY_PROTO(( char *, GUC_yyconst char *, int ));
#endif
#ifdef YY_NEED_STRLEN
static int GUC_yy_flex_strlen YY_PROTO(( GUC_yyconst char * ));
#endif
#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int GUC_yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif
#if YY_STACK_USED
static int GUC_yy_start_stack_ptr = 0;
static int GUC_yy_start_stack_depth = 0;
static int *GUC_yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void GUC_yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void GUC_yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int GUC_yy_top_state YY_PROTO(( void ));
#endif
#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif
#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( GUC_yytext, GUC_yyleng, 1, GUC_yyout )
#endif
/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
       if ( GUC_yy_current_buffer->GUC_yy_is_interactive ) \
             { \
             int c = '*', n; \
             for ( n = 0; n < max_size && \
                       (c = getc( GUC_yyin )) != EOF && c != '\n'; ++n ) \
                  buf[n] = (char) c; \
             if ( c == '\n' ) \
                  buf[n++] = (char) c; \
             if ( c == EOF && ferror( GUC_yyin ) ) \
                  YY_FATAL_ERROR( "input in flex scanner failed" ); \
             result = n; \
             } \
       else if ( ((result = fread( buf, 1, max_size, GUC_yyin )) == 0) \
               && ferror( GUC_yyin ) ) \
             YY_FATAL_ERROR( "input in flex scanner failed" );
#endif
/* No semi-colon after return; correct usage is to write "GUC_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef GUC_yyterminate
#define GUC_yyterminate() return YY_NULL
#endif
/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif
/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) GUC_yy_fatal_error( msg )
#endif
/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int GUC_yylex YY_PROTO(( void ))
#endif
/* Code executed at the beginning of each rule, after GUC_yytext and GUC_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif
/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif
#define YY_RULE_SETUP \
       YY_USER_ACTION
YY_DECL {
       register GUC_yy_state_type GUC_yy_current_state;
       register char *GUC_yy_cp, *GUC_yy_bp;
       register int GUC_yy_act;
       if ( GUC_yy_init ) {
             GUC_yy_init = 0;
#ifdef YY_USER_INIT
             YY_USER_INIT;
#endif
             if ( ! GUC_yy_start )
                  GUC_yy_start = 1;   /* first start state */
             if ( ! GUC_yyin )
                  GUC_yyin = stdin;
             if ( ! GUC_yyout )
                  GUC_yyout = stdout;
             if ( ! GUC_yy_current_buffer )
                  GUC_yy_current_buffer =
                      GUC_yy_create_buffer( GUC_yyin, YY_BUF_SIZE );
             GUC_yy_load_buffer_state(); }
       while ( 1 )     /* loops until end-of-file is reached */ {
             GUC_yy_cp = GUC_yy_c_buf_p;
             /* Support of GUC_yytext. */
             *GUC_yy_cp = GUC_yy_hold_char;
             /* GUC_yy_bp points to the position in GUC_yy_ch_buf of the start of
              * the current run.
              */
             GUC_yy_bp = GUC_yy_cp;
             GUC_yy_current_state = GUC_yy_start;
GUC_yy_match:
             do {
                  register YY_CHAR GUC_yy_c = GUC_yy_ec[YY_SC_TO_UI(*GUC_yy_cp)];
                  if ( GUC_yy_accept[GUC_yy_current_state] ) {
                      GUC_yy_last_accepting_state = GUC_yy_current_state;
                      GUC_yy_last_accepting_cpos = GUC_yy_cp; }
                  while ( GUC_yy_chk[GUC_yy_base[GUC_yy_current_state] + GUC_yy_c] != GUC_yy_current_state ) {
                      GUC_yy_current_state = (int) GUC_yy_def[GUC_yy_current_state];
                      if ( GUC_yy_current_state >= 38 )
                         GUC_yy_c = GUC_yy_meta[(unsigned int) GUC_yy_c]; }
                  GUC_yy_current_state = GUC_yy_nxt[GUC_yy_base[GUC_yy_current_state] + (unsigned int) GUC_yy_c];
                  ++GUC_yy_cp; }
             while ( GUC_yy_base[GUC_yy_current_state] != 86 );
GUC_yy_find_action:
             GUC_yy_act = GUC_yy_accept[GUC_yy_current_state];
             if ( GUC_yy_act == 0 )
                  { /* have to back up */
                  GUC_yy_cp = GUC_yy_last_accepting_cpos;
                  GUC_yy_current_state = GUC_yy_last_accepting_state;
                  GUC_yy_act = GUC_yy_accept[GUC_yy_current_state]; }
             YY_DO_BEFORE_ACTION;
do_action:     /* This label is used only to access EOF actions. */
             switch ( GUC_yy_act )
       { /* beginning of action switch */
                  case 0: /* must back up */
                  /* undo the effects of YY_DO_BEFORE_ACTION */
                  *GUC_yy_cp = GUC_yy_hold_char;
                  GUC_yy_cp = GUC_yy_last_accepting_cpos;
                  GUC_yy_current_state = GUC_yy_last_accepting_state;
                  goto GUC_yy_find_action;
case 1:
YY_RULE_SETUP
ConfigFileLineno++; return GUC_EOL;
       YY_BREAK
case 2:
YY_RULE_SETUP
/* eat whitespace */
       YY_BREAK
case 3:
*GUC_yy_cp = GUC_yy_hold_char; /* undo effects of setting up GUC_yytext */
GUC_yy_c_buf_p = GUC_yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up GUC_yytext again */
YY_RULE_SETUP
/* eat comment */
       YY_BREAK
case 4:
YY_RULE_SETUP
return GUC_ID;
       YY_BREAK
case 5:
YY_RULE_SETUP
return GUC_STRING;
       YY_BREAK
case 6:
YY_RULE_SETUP
return GUC_UNQUOTED_STRING;
       YY_BREAK
case 7:
YY_RULE_SETUP
return GUC_INTEGER;
       YY_BREAK
case 8:
YY_RULE_SETUP
return GUC_REAL;
       YY_BREAK
case 9:
YY_RULE_SETUP
return GUC_EQUALS;
       YY_BREAK
case 10:
YY_RULE_SETUP
return GUC_ERROR;
       YY_BREAK
case 11:
YY_RULE_SETUP
ECHO;
       YY_BREAK
case YY_STATE_EOF(INITIAL):
       GUC_yyterminate();
       case YY_END_OF_BUFFER: {
             /* Amount of text matched not including the EOB char. */
             int GUC_yy_amount_of_matched_text = (int) (GUC_yy_cp - GUC_yytext_ptr) - 1;
             /* Undo the effects of YY_DO_BEFORE_ACTION. */
             *GUC_yy_cp = GUC_yy_hold_char;
             YY_RESTORE_YY_MORE_OFFSET
             if ( GUC_yy_current_buffer->GUC_yy_buffer_status == YY_BUFFER_NEW ) {
                  /* We're scanning a new file or input source.  It's
                   * possible that this happened because the user
                   * just pointed GUC_yyin at a new source and called
                   * GUC_yylex().  If so, then we have to assure
                   * consistency between GUC_yy_current_buffer and our
                   * globals.  Here is the right place to do so, because
                   * this is the first action (other than possibly a
                   * back-up) that will match for the new input source.
                   */
                  GUC_yy_n_chars = GUC_yy_current_buffer->GUC_yy_n_chars;
                  GUC_yy_current_buffer->GUC_yy_input_file = GUC_yyin;
                  GUC_yy_current_buffer->GUC_yy_buffer_status = YY_BUFFER_NORMAL; }
             /* Note that here we test for GUC_yy_c_buf_p "<=" to the position
              * of the first EOB in the buffer, since GUC_yy_c_buf_p will
              * already have been incremented past the NUL character
              * (since all states make transitions on EOB to the
              * end-of-buffer state).  Contrast this with the test
              * in input().
              */
             if ( GUC_yy_c_buf_p <= &GUC_yy_current_buffer->GUC_yy_ch_buf[GUC_yy_n_chars] )
                  { /* This was really a NUL. */
                  GUC_yy_state_type GUC_yy_next_state;
                  GUC_yy_c_buf_p = GUC_yytext_ptr + GUC_yy_amount_of_matched_text;
                  GUC_yy_current_state = GUC_yy_get_previous_state();
                  /* Okay, we're now positioned to make the NUL
                   * transition.  We couldn't have
                   * GUC_yy_get_previous_state() go ahead and do it
                   * for us because it doesn't know how to deal
                   * with the possibility of jamming (and we don't
                   * want to build jamming into it because then it
                   * will run more slowly).
                   */
                  GUC_yy_next_state = GUC_yy_try_NUL_trans( GUC_yy_current_state );
                  GUC_yy_bp = GUC_yytext_ptr + YY_MORE_ADJ;
                  if ( GUC_yy_next_state ) {
                      /* Consume the NUL. */
                      GUC_yy_cp = ++GUC_yy_c_buf_p;
                      GUC_yy_current_state = GUC_yy_next_state;
                      goto GUC_yy_match; }
                  else {
                      GUC_yy_cp = GUC_yy_c_buf_p;
                      goto GUC_yy_find_action; } }
             else switch ( GUC_yy_get_next_buffer() ) {
                  case EOB_ACT_END_OF_FILE: {
                      GUC_yy_did_buffer_switch_on_eof = 0;
                      if ( GUC_yywrap() ) {
                         /* Note: because we've taken care in
                          * GUC_yy_get_next_buffer() to have set up
                          * GUC_yytext, we can now set up
                          * GUC_yy_c_buf_p so that if some total
                          * hoser (like flex itself) wants to
                          * call the scanner after we return the
                          * YY_NULL, it'll still work - another
                          * YY_NULL will get returned.
                          */
                         GUC_yy_c_buf_p = GUC_yytext_ptr + YY_MORE_ADJ;
                         GUC_yy_act = YY_STATE_EOF(YY_START);
                         goto do_action; }
                      else {
                         if ( ! GUC_yy_did_buffer_switch_on_eof )
                           YY_NEW_FILE; }
                      break; }
                  case EOB_ACT_CONTINUE_SCAN:
                      GUC_yy_c_buf_p =
                         GUC_yytext_ptr + GUC_yy_amount_of_matched_text;
                      GUC_yy_current_state = GUC_yy_get_previous_state();
                      GUC_yy_cp = GUC_yy_c_buf_p;
                      GUC_yy_bp = GUC_yytext_ptr + YY_MORE_ADJ;
                      goto GUC_yy_match;
                  case EOB_ACT_LAST_MATCH:
                      GUC_yy_c_buf_p =
                      &GUC_yy_current_buffer->GUC_yy_ch_buf[GUC_yy_n_chars];
                      GUC_yy_current_state = GUC_yy_get_previous_state();
                      GUC_yy_cp = GUC_yy_c_buf_p;
                      GUC_yy_bp = GUC_yytext_ptr + YY_MORE_ADJ;
                      goto GUC_yy_find_action; }
             break; }
       default:
             YY_FATAL_ERROR(
                  "fatal flex scanner internal error--no action found" );
       } /* end of action switch */
             } /* end of scanning one token */
       } /* end of GUC_yylex */
/* GUC_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *     EOB_ACT_LAST_MATCH -
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
static int GUC_yy_get_next_buffer() {
       register char *dest = GUC_yy_current_buffer->GUC_yy_ch_buf;
       register char *source = GUC_yytext_ptr;
       register int number_to_move, i;
       int ret_val;
       if ( GUC_yy_c_buf_p > &GUC_yy_current_buffer->GUC_yy_ch_buf[GUC_yy_n_chars + 1] )
             YY_FATAL_ERROR(
             "fatal flex scanner internal error--end of buffer missed" );
       if ( GUC_yy_current_buffer->GUC_yy_fill_buffer == 0 )
             { /* Don't try to fill the buffer, so this is an EOF. */
             if ( GUC_yy_c_buf_p - GUC_yytext_ptr - YY_MORE_ADJ == 1 ) {
                  /* We matched a single character, the EOB, so
                   * treat this as a final EOF.
                   */
                  return EOB_ACT_END_OF_FILE; }
             else {
                  /* We matched some text prior to the EOB, first
                   * process it.
                   */
                  return EOB_ACT_LAST_MATCH; } }
       /* Try to read more data. */
       /* First move last chars to start of buffer. */
       number_to_move = (int) (GUC_yy_c_buf_p - GUC_yytext_ptr) - 1;
       for ( i = 0; i < number_to_move; ++i )
             *(dest++) = *(source++);
       if ( GUC_yy_current_buffer->GUC_yy_buffer_status == YY_BUFFER_EOF_PENDING )
             /* don't do the read, it's not guaranteed to return an EOF,
              * just force an EOF
              */
             GUC_yy_current_buffer->GUC_yy_n_chars = GUC_yy_n_chars = 0;
       else {
             int num_to_read =
                  GUC_yy_current_buffer->GUC_yy_buf_size - number_to_move - 1;
             while ( num_to_read <= 0 )
                  { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
                  YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else
                  /* just a shorter name for the current buffer */
                  YY_BUFFER_STATE b = GUC_yy_current_buffer;
                  int GUC_yy_c_buf_p_offset =
                      (int) (GUC_yy_c_buf_p - b->GUC_yy_ch_buf);
                  if ( b->GUC_yy_is_our_buffer ) {
                      int new_size = b->GUC_yy_buf_size * 2;
                      if ( new_size <= 0 )
                         b->GUC_yy_buf_size += b->GUC_yy_buf_size / 8;
                      else
                         b->GUC_yy_buf_size *= 2;
                      b->GUC_yy_ch_buf = (char *)
                         /* Include room in for 2 EOB chars. */
                         GUC_yy_flex_realloc( (void *) b->GUC_yy_ch_buf,
                             b->GUC_yy_buf_size + 2 ); }
                  else
                      /* Can't grow it, we don't own it. */
                      b->GUC_yy_ch_buf = 0;
                  if ( ! b->GUC_yy_ch_buf )
                      YY_FATAL_ERROR(
                      "fatal error - scanner input buffer overflow" );
                  GUC_yy_c_buf_p = &b->GUC_yy_ch_buf[GUC_yy_c_buf_p_offset];
                  num_to_read = GUC_yy_current_buffer->GUC_yy_buf_size -
                           number_to_move - 1;
#endif
                  }
             if ( num_to_read > YY_READ_BUF_SIZE )
                  num_to_read = YY_READ_BUF_SIZE;
             /* Read in more data. */
             YY_INPUT( (&GUC_yy_current_buffer->GUC_yy_ch_buf[number_to_move]),
                  GUC_yy_n_chars, num_to_read );
             GUC_yy_current_buffer->GUC_yy_n_chars = GUC_yy_n_chars; }
       if ( GUC_yy_n_chars == 0 ) {
             if ( number_to_move == YY_MORE_ADJ ) {
                  ret_val = EOB_ACT_END_OF_FILE;
                  GUC_yyrestart( GUC_yyin ); }
             else {
                  ret_val = EOB_ACT_LAST_MATCH;
                  GUC_yy_current_buffer->GUC_yy_buffer_status =
                      YY_BUFFER_EOF_PENDING; } }
       else
             ret_val = EOB_ACT_CONTINUE_SCAN;
       GUC_yy_n_chars += number_to_move;
       GUC_yy_current_buffer->GUC_yy_ch_buf[GUC_yy_n_chars] = YY_END_OF_BUFFER_CHAR;
       GUC_yy_current_buffer->GUC_yy_ch_buf[GUC_yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
       GUC_yytext_ptr = &GUC_yy_current_buffer->GUC_yy_ch_buf[0];
       return ret_val; }
/* GUC_yy_get_previous_state - get the state just before the EOB char was reached */
static GUC_yy_state_type GUC_yy_get_previous_state() {
       register GUC_yy_state_type GUC_yy_current_state;
       register char *GUC_yy_cp;
       GUC_yy_current_state = GUC_yy_start;
       for ( GUC_yy_cp = GUC_yytext_ptr + YY_MORE_ADJ; GUC_yy_cp < GUC_yy_c_buf_p; ++GUC_yy_cp ) {
             register YY_CHAR GUC_yy_c = (*GUC_yy_cp ? GUC_yy_ec[YY_SC_TO_UI(*GUC_yy_cp)] : 1);
             if ( GUC_yy_accept[GUC_yy_current_state] ) {
                  GUC_yy_last_accepting_state = GUC_yy_current_state;
                  GUC_yy_last_accepting_cpos = GUC_yy_cp; }
             while ( GUC_yy_chk[GUC_yy_base[GUC_yy_current_state] + GUC_yy_c] != GUC_yy_current_state ) {
                  GUC_yy_current_state = (int) GUC_yy_def[GUC_yy_current_state];
                  if ( GUC_yy_current_state >= 38 )
                      GUC_yy_c = GUC_yy_meta[(unsigned int) GUC_yy_c]; }
             GUC_yy_current_state = GUC_yy_nxt[GUC_yy_base[GUC_yy_current_state] + (unsigned int) GUC_yy_c]; }
       return GUC_yy_current_state; }
/* GUC_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = GUC_yy_try_NUL_trans( current_state );
 */
#ifdef YY_USE_PROTOS
static GUC_yy_state_type GUC_yy_try_NUL_trans( GUC_yy_state_type GUC_yy_current_state )
#else
static GUC_yy_state_type GUC_yy_try_NUL_trans( GUC_yy_current_state )
GUC_yy_state_type GUC_yy_current_state;
#endif
       {
       register int GUC_yy_is_jam;
       register char *GUC_yy_cp = GUC_yy_c_buf_p;
       register YY_CHAR GUC_yy_c = 1;
       if ( GUC_yy_accept[GUC_yy_current_state] ) {
             GUC_yy_last_accepting_state = GUC_yy_current_state;
             GUC_yy_last_accepting_cpos = GUC_yy_cp; }
       while ( GUC_yy_chk[GUC_yy_base[GUC_yy_current_state] + GUC_yy_c] != GUC_yy_current_state ) {
             GUC_yy_current_state = (int) GUC_yy_def[GUC_yy_current_state];
             if ( GUC_yy_current_state >= 38 )
                  GUC_yy_c = GUC_yy_meta[(unsigned int) GUC_yy_c]; }
       GUC_yy_current_state = GUC_yy_nxt[GUC_yy_base[GUC_yy_current_state] + (unsigned int) GUC_yy_c];
       GUC_yy_is_jam = (GUC_yy_current_state == 37);
       return GUC_yy_is_jam ? 0 : GUC_yy_current_state; }
#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void GUC_yyunput( int c, register char *GUC_yy_bp )
#else
static void GUC_yyunput( c, GUC_yy_bp )
int c;
register char *GUC_yy_bp;
#endif
       {
       register char *GUC_yy_cp = GUC_yy_c_buf_p;
       /* undo effects of setting up GUC_yytext */
       *GUC_yy_cp = GUC_yy_hold_char;
       if ( GUC_yy_cp < GUC_yy_current_buffer->GUC_yy_ch_buf + 2 )
             { /* need to shift things up to make room */
             /* +2 for EOB chars. */
             register int number_to_move = GUC_yy_n_chars + 2;
             register char *dest = &GUC_yy_current_buffer->GUC_yy_ch_buf[
                         GUC_yy_current_buffer->GUC_yy_buf_size + 2];
             register char *source =
                      &GUC_yy_current_buffer->GUC_yy_ch_buf[number_to_move];
             while ( source > GUC_yy_current_buffer->GUC_yy_ch_buf )
                  *--dest = *--source;
             GUC_yy_cp += (int) (dest - source);
             GUC_yy_bp += (int) (dest - source);
             GUC_yy_current_buffer->GUC_yy_n_chars =
                  GUC_yy_n_chars = GUC_yy_current_buffer->GUC_yy_buf_size;
             if ( GUC_yy_cp < GUC_yy_current_buffer->GUC_yy_ch_buf + 2 )
                  YY_FATAL_ERROR( "flex scanner push-back overflow" ); }
       *--GUC_yy_cp = (char) c;
       GUC_yytext_ptr = GUC_yy_bp;
       GUC_yy_hold_char = *GUC_yy_cp;
       GUC_yy_c_buf_p = GUC_yy_cp; }
#endif /* ifndef YY_NO_UNPUT */
#ifdef __cplusplus
static int GUC_yyinput()
#else
static int input()
#endif
       {
       int c;
       *GUC_yy_c_buf_p = GUC_yy_hold_char;
       if ( *GUC_yy_c_buf_p == YY_END_OF_BUFFER_CHAR ) {
             /* GUC_yy_c_buf_p now points to the character we want to return.
              * If this occurs *before* the EOB characters, then it's a
              * valid NUL; if not, then we've hit the end of the buffer.
              */
             if ( GUC_yy_c_buf_p < &GUC_yy_current_buffer->GUC_yy_ch_buf[GUC_yy_n_chars] )
                  /* This was really a NUL. */
                  *GUC_yy_c_buf_p = '\0';
             else
                  { /* need more input */
                  int offset = GUC_yy_c_buf_p - GUC_yytext_ptr;
                  ++GUC_yy_c_buf_p;
                  switch ( GUC_yy_get_next_buffer() ) {
                      case EOB_ACT_LAST_MATCH:
                         /* This happens because GUC_yy_g_n_b()
                          * sees that we've accumulated a
                          * token and flags that we need to
                          * try matching the token before
                          * proceeding.  But for input(),
                          * there's no matching to consider.
                          * So convert the EOB_ACT_LAST_MATCH
                          * to EOB_ACT_END_OF_FILE.
                          */
                         /* Reset buffer status. */
                         GUC_yyrestart( GUC_yyin );
                         /* fall through */
                      case EOB_ACT_END_OF_FILE: {
                         if ( GUC_yywrap() )
                           return EOF;
                         if ( ! GUC_yy_did_buffer_switch_on_eof )
                           YY_NEW_FILE;
#ifdef __cplusplus
                         return GUC_yyinput();
#else
                         return input();
#endif
                         }
                      case EOB_ACT_CONTINUE_SCAN:
                         GUC_yy_c_buf_p = GUC_yytext_ptr + offset;
                         break; } } }
       c = *(unsigned char *) GUC_yy_c_buf_p;        /* cast for 8-bit char's */
       *GUC_yy_c_buf_p = '\0';       /* preserve GUC_yytext */
       GUC_yy_hold_char = *++GUC_yy_c_buf_p;
       return c; }
#ifdef YY_USE_PROTOS
void GUC_yyrestart( FILE *input_file )
#else
void GUC_yyrestart( input_file )
FILE *input_file;
#endif
       {
       if ( ! GUC_yy_current_buffer )
             GUC_yy_current_buffer = GUC_yy_create_buffer( GUC_yyin, YY_BUF_SIZE );
       GUC_yy_init_buffer( GUC_yy_current_buffer, input_file );
       GUC_yy_load_buffer_state(); }
#ifdef YY_USE_PROTOS
void GUC_yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void GUC_yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
       {
       if ( GUC_yy_current_buffer == new_buffer )
             return;
       if ( GUC_yy_current_buffer ) {
             /* Flush out information for old buffer. */
             *GUC_yy_c_buf_p = GUC_yy_hold_char;
             GUC_yy_current_buffer->GUC_yy_buf_pos = GUC_yy_c_buf_p;
             GUC_yy_current_buffer->GUC_yy_n_chars = GUC_yy_n_chars; }
       GUC_yy_current_buffer = new_buffer;
       GUC_yy_load_buffer_state();
       /* We don't actually know whether we did this switch during
        * EOF (GUC_yywrap()) processing, but the only time this flag
        * is looked at is after GUC_yywrap() is called, so it's safe
        * to go ahead and always set it.
        */
       GUC_yy_did_buffer_switch_on_eof = 1; }
#ifdef YY_USE_PROTOS
void GUC_yy_load_buffer_state( void )
#else
void GUC_yy_load_buffer_state()
#endif
       {
       GUC_yy_n_chars = GUC_yy_current_buffer->GUC_yy_n_chars;
       GUC_yytext_ptr = GUC_yy_c_buf_p = GUC_yy_current_buffer->GUC_yy_buf_pos;
       GUC_yyin = GUC_yy_current_buffer->GUC_yy_input_file;
       GUC_yy_hold_char = *GUC_yy_c_buf_p; }
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE GUC_yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE GUC_yy_create_buffer( file, size )
FILE *file;
int size;
#endif
       {
       YY_BUFFER_STATE b;
       b = (YY_BUFFER_STATE) GUC_yy_flex_alloc( sizeof( struct GUC_yy_buffer_state ) );
       if ( ! b )
             YY_FATAL_ERROR( "out of dynamic memory in GUC_yy_create_buffer()" );
       b->GUC_yy_buf_size = size;
       /* GUC_yy_ch_buf has to be 2 characters longer than the size given because
        * we need to put in 2 end-of-buffer characters.
        */
       b->GUC_yy_ch_buf = (char *) GUC_yy_flex_alloc( b->GUC_yy_buf_size + 2 );
       if ( ! b->GUC_yy_ch_buf )
             YY_FATAL_ERROR( "out of dynamic memory in GUC_yy_create_buffer()" );
       b->GUC_yy_is_our_buffer = 1;
       GUC_yy_init_buffer( b, file );
       return b; }
#ifdef YY_USE_PROTOS
void GUC_yy_delete_buffer( YY_BUFFER_STATE b )
#else
void GUC_yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
       {
       if ( ! b )
             return;
       if ( b == GUC_yy_current_buffer )
             GUC_yy_current_buffer = (YY_BUFFER_STATE) 0;
       if ( b->GUC_yy_is_our_buffer )
             GUC_yy_flex_free( (void *) b->GUC_yy_ch_buf );
       GUC_yy_flex_free( (void *) b ); }
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#ifdef YY_USE_PROTOS
void GUC_yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void GUC_yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
       {
       GUC_yy_flush_buffer( b );
       b->GUC_yy_input_file = file;
       b->GUC_yy_fill_buffer = 1;
#if YY_ALWAYS_INTERACTIVE
       b->GUC_yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
       b->GUC_yy_is_interactive = 0;
#else
       b->GUC_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
       }
#ifdef YY_USE_PROTOS
void GUC_yy_flush_buffer( YY_BUFFER_STATE b )
#else
void GUC_yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif
       {
       if ( ! b )
             return;
       b->GUC_yy_n_chars = 0;
       /* We always need two end-of-buffer characters.  The first causes
        * a transition to the end-of-buffer state.  The second causes
        * a jam in that state.
        */
       b->GUC_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
       b->GUC_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
       b->GUC_yy_buf_pos = &b->GUC_yy_ch_buf[0];
       b->GUC_yy_at_bol = 1;
       b->GUC_yy_buffer_status = YY_BUFFER_NEW;
       if ( b == GUC_yy_current_buffer )
             GUC_yy_load_buffer_state(); }
#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE GUC_yy_scan_buffer( char *base, GUC_yy_size_t size )
#else
YY_BUFFER_STATE GUC_yy_scan_buffer( base, size )
char *base;
GUC_yy_size_t size;
#endif
       {
       YY_BUFFER_STATE b;
       if ( size < 2 ||
            base[size-2] != YY_END_OF_BUFFER_CHAR ||
            base[size-1] != YY_END_OF_BUFFER_CHAR )
             /* They forgot to leave room for the EOB's. */
             return 0;
       b = (YY_BUFFER_STATE) GUC_yy_flex_alloc( sizeof( struct GUC_yy_buffer_state ) );
       if ( ! b )
             YY_FATAL_ERROR( "out of dynamic memory in GUC_yy_scan_buffer()" );
       b->GUC_yy_buf_size = size - 2;        /* "- 2" to take care of EOB's */
       b->GUC_yy_buf_pos = b->GUC_yy_ch_buf = base;
       b->GUC_yy_is_our_buffer = 0;
       b->GUC_yy_input_file = 0;
       b->GUC_yy_n_chars = b->GUC_yy_buf_size;
       b->GUC_yy_is_interactive = 0;
       b->GUC_yy_at_bol = 1;
       b->GUC_yy_fill_buffer = 0;
       b->GUC_yy_buffer_status = YY_BUFFER_NEW;
       GUC_yy_switch_to_buffer( b );
       return b; }
#endif
#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE GUC_yy_scan_string( GUC_yyconst char *GUC_yy_str )
#else
YY_BUFFER_STATE GUC_yy_scan_string( GUC_yy_str )
GUC_yyconst char *GUC_yy_str;
#endif
       {
       int len;
       for ( len = 0; GUC_yy_str[len]; ++len )
             ;
       return GUC_yy_scan_bytes( GUC_yy_str, len ); }
#endif
#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE GUC_yy_scan_bytes( GUC_yyconst char *bytes, int len )
#else
YY_BUFFER_STATE GUC_yy_scan_bytes( bytes, len )
GUC_yyconst char *bytes;
int len;
#endif
       {
       YY_BUFFER_STATE b;
       char *buf;
       GUC_yy_size_t n;
       int i;
       /* Get memory for full buffer, including space for trailing EOB's. */
       n = len + 2;
       buf = (char *) GUC_yy_flex_alloc( n );
       if ( ! buf )
             YY_FATAL_ERROR( "out of dynamic memory in GUC_yy_scan_bytes()" );
       for ( i = 0; i < len; ++i )
             buf[i] = bytes[i];
       buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;
       b = GUC_yy_scan_buffer( buf, n );
       if ( ! b )
             YY_FATAL_ERROR( "bad buffer in GUC_yy_scan_bytes()" );
       /* It's okay to grow etc. this buffer, and we should throw it
        * away when we're done.
        */
       b->GUC_yy_is_our_buffer = 1;
       return b; }
#endif
#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void GUC_yy_push_state( int new_state )
#else
static void GUC_yy_push_state( new_state )
int new_state;
#endif
       {
       if ( GUC_yy_start_stack_ptr >= GUC_yy_start_stack_depth ) {
             GUC_yy_size_t new_size;
             GUC_yy_start_stack_depth += YY_START_STACK_INCR;
             new_size = GUC_yy_start_stack_depth * sizeof( int );
             if ( ! GUC_yy_start_stack )
                  GUC_yy_start_stack = (int *) GUC_yy_flex_alloc( new_size );
             else
                  GUC_yy_start_stack = (int *) GUC_yy_flex_realloc(
                         (void *) GUC_yy_start_stack, new_size );
             if ( ! GUC_yy_start_stack )
                  YY_FATAL_ERROR(
                  "out of memory expanding start-condition stack" ); }
       GUC_yy_start_stack[GUC_yy_start_stack_ptr++] = YY_START;
       BEGIN(new_state); }
#endif
#ifndef YY_NO_POP_STATE
static void GUC_yy_pop_state() {
       if ( --GUC_yy_start_stack_ptr < 0 )
             YY_FATAL_ERROR( "start-condition stack underflow" );
       BEGIN(GUC_yy_start_stack[GUC_yy_start_stack_ptr]); }
#endif
#ifndef YY_NO_TOP_STATE
static int GUC_yy_top_state() {
       return GUC_yy_start_stack[GUC_yy_start_stack_ptr - 1]; }
#endif
#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif
#ifdef YY_USE_PROTOS
static void GUC_yy_fatal_error( GUC_yyconst char msg[] )
#else
static void GUC_yy_fatal_error( msg )
char msg[];
#endif
       {
       (void) fprintf( stderr, "%s\n", msg );
       exit( YY_EXIT_FAILURE ); }
/* Redefine GUC_yyless() so it works in section 3 code. */
#undef GUC_yyless
#define GUC_yyless(n) \
       do \
             { \
             /* Undo effects of setting up GUC_yytext. */ \
             GUC_yytext[GUC_yyleng] = GUC_yy_hold_char; \
             GUC_yy_c_buf_p = GUC_yytext + n; \
             GUC_yy_hold_char = *GUC_yy_c_buf_p; \
             *GUC_yy_c_buf_p = '\0'; \
             GUC_yyleng = n; \
             } \
       while ( 0 )
/* Internal utility routines. */
#ifndef GUC_yytext_ptr
#ifdef YY_USE_PROTOS
static void GUC_yy_flex_strncpy( char *s1, GUC_yyconst char *s2, int n )
#else
static void GUC_yy_flex_strncpy( s1, s2, n )
char *s1;
GUC_yyconst char *s2;
int n;
#endif
       {
       register int i;
       for ( i = 0; i < n; ++i )
             s1[i] = s2[i]; }
#endif
#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int GUC_yy_flex_strlen( GUC_yyconst char *s )
#else
static int GUC_yy_flex_strlen( s )
GUC_yyconst char *s;
#endif
       {
       register int n;
       for ( n = 0; s[n]; ++n )
             ;
       return n; }
#endif
#ifdef YY_USE_PROTOS
static void *GUC_yy_flex_alloc( GUC_yy_size_t size )
#else
static void *GUC_yy_flex_alloc( size )
GUC_yy_size_t size;
#endif
       {
       return (void *) malloc( size ); }
#ifdef YY_USE_PROTOS
static void *GUC_yy_flex_realloc( void *ptr, GUC_yy_size_t size )
#else
static void *GUC_yy_flex_realloc( ptr, size )
void *ptr;
GUC_yy_size_t size;
#endif
       {
       /* The cast to (char *) in the following accommodates both
        * implementations that use char* generic pointers, and those
        * that use void* generic pointers.  It works with the latter
        * because both ANSI C and C++ allow castless assignment from
        * any pointer type to void*, and deal with argument conversions
        * as though doing an assignment.
        */
       return (void *) realloc( (char *) ptr, size ); }
#ifdef YY_USE_PROTOS
static void GUC_yy_flex_free( void *ptr )
#else
static void GUC_yy_flex_free( ptr )
void *ptr;
#endif
       {
       free( ptr ); }
#if YY_MAIN
int main() {
       GUC_yylex();
       return 0; }
#endif
struct name_value_pair {
       char       *name;
       char       *value;
       struct name_value_pair *next;
};
/*
 * Free a list of name/value pairs, including the names and the values
 */
static void
free_name_value_list(struct name_value_pair * list) {
       struct name_value_pair *item;
       item = list;
       while (item) {
             struct name_value_pair *save;
             save = item->next;
             free(item->name);
             free(item->value);
             free(item);
             item = save; } }
/*
 * Official function to read and process the configuration file. The
 * parameter indicates in what context the file is being read
 * (postmaster startup, backend startup, or SIGHUP). All options
 * mentioned in the configuration file are set to new values. This
 * function does not return if an error occurs. If an error occurs, no
 * values will be changed.
 */
void
ProcessConfigFile(GucContext context) {
       int token, parse_state;
       char *opt_name, *opt_value;
       char *filename;
       struct name_value_pair *item, *head, *tail;
       int elevel;
       FILE * fp;
       Assert(context == PGC_POSTMASTER || context == PGC_BACKEND 
             || context == PGC_SIGHUP);
       Assert(DataDir);
       elevel = (context == PGC_SIGHUP) ? DEBUG : ERROR;
       /*
        * Open file
        */
       filename = malloc(strlen(DataDir) + strlen(CONFIG_FILENAME) + 2);
       if (filename == NULL) {
             elog(elevel, "out of memory");
             return; }
       sprintf(filename, "%s/" CONFIG_FILENAME, DataDir);
    fp = AllocateFile(filename, "r");
    if (!fp) {
             free(filename);
        /* File not found is fine */
        if (errno != ENOENT)
            elog(elevel, "could not read configuration file `" CONFIG_FILENAME "': %s", strerror(errno));
             return; }
       /*
        * Parse
        */
       GUC_yyin = fp;
    parse_state = 0;
       head = tail = NULL;
       opt_name = opt_value = NULL;
    while((token = GUC_yylex()))
        switch(parse_state) {
            case 0: /* no previous input */
                if (token == GUC_EOL) /* empty line */
                    continue;
                if (token != GUC_ID)
                    goto parse_error;
                opt_name = strdup(GUC_yytext);
                      if (opt_name == NULL)
                         goto out_of_memory;
                parse_state = 1;
                break;
            case 1: /* found name */
                /* ignore equals sign */
                if (token == GUC_EQUALS)
                    token = GUC_yylex();
                if (token != GUC_ID && token != GUC_STRING && 
                  token != GUC_INTEGER && token != GUC_REAL && 
                  token != GUC_UNQUOTED_STRING)
                    goto parse_error;
                opt_value = strdup(GUC_yytext);
                      if (opt_value == NULL)
                         goto out_of_memory;
             if (token == GUC_STRING) {
                  /* remove the beginning and ending quote/apostrophe */
                  /* first: shift the whole shooting match down one
                character */
                  memmove(opt_value,opt_value+1,strlen(opt_value)-1);
                  /* second: null out the 2 characters we shifted */
                        opt_value[strlen(opt_value)-2]='\0';
                  /* do the escape thing.  free()'s the strdup above */
                  opt_value=GUC_scanstr(opt_value); }
                parse_state = 2;
                break;
            case 2: /* now we'd like an end of line */
                      if (token != GUC_EOL)
                         goto parse_error;
                      /* append to list */
                      item = malloc(sizeof *item);
                      if (item == NULL)
                         goto out_of_memory;
                      item->name = opt_name;
                      item->value = opt_value;
                      item->next = NULL;
                      if (!head)
                         tail = head = item;
                      else {
                         tail->next = item;
                         tail = item; }
                parse_state = 0;
                break; }
       FreeFile(fp);
       free(filename);
       /*
        * Check if all options are valid
        */
    for(item = head; item; item=item->next) {
             if (!set_config_option(item->name, item->value, context, false, false))
                  goto cleanup_exit; }
    /* If we got here all the options parsed okay. */
       for(item = head; item; item=item->next)
             set_config_option(item->name, item->value, context, true, true);
 cleanup_exit:
       free_name_value_list(head);
       return;
 parse_error:
       FreeFile(fp);
       free(filename);
       free_name_value_list(head);
       elog(elevel, CONFIG_FILENAME ":%u: syntax error, token=\"%s\"", 
             ConfigFileLineno,GUC_yytext);
       return;
 out_of_memory:
       FreeFile(fp);
       free(filename);
       free_name_value_list(head);
       elog(elevel, "out of memory");
       return; }
int
GUC_yywrap(void) {
       return 1; }
/* ----------------
 *         scanstr
 *
 * if the string passed in has escaped codes, map the escape codes to actual
 * chars
 *
 * the string returned is malloc'd and should eventually be free'd by the
 * caller!
 * ----------------
 */
char *
GUC_scanstr(char *s) {
       char     *newStr;
       int      len,
                      i,
                      j;
       if (s == NULL || s[0] == '\0') {
             if (s != NULL) free (s);
             return strdup(""); }
       len = strlen(s);
       newStr = malloc(len + 1);     /* string cannot get longer */
       if (newStr == NULL)
             elog(FATAL, "out of memory");
       for (i = 0, j = 0; i < len; i++) {
             if (s[i] == '\\') {
                  i++;
                  switch (s[i]) {
                      case 'b':
                         newStr[j] = '\b';
                         break;
                      case 'f':
                         newStr[j] = '\f';
                         break;
                      case 'n':
                         newStr[j] = '\n';
                         break;
                      case 'r':
                         newStr[j] = '\r';
                         break;
                      case 't':
                         newStr[j] = '\t';
                         break;
                      case '0':
                      case '1':
                      case '2':
                      case '3':
                      case '4':
                      case '5':
                      case '6':
                      case '7': {
                           int               k;
                           long         octVal = 0;
                           for (k = 0;
                             s[i + k] >= '0' && s[i + k] <= '7' && k < 3;
                             k++)
                            octVal = (octVal << 3) + (s[i + k] - '0');
                           i += k - 1;
                           newStr[j] = ((char) octVal); }
                         break;
                      default:
                         newStr[j] = s[i];
                         break; }
                  }                     /* switch */
             else
                  newStr[j] = s[i];
             j++; }
       newStr[j] = '\0';
       free(s);
       return newStr; }
