/* A lexical scanner generated by flex */
/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 * $FreeBSD: src/usr.bin/lex/flex.skl,v 1.4 1999/10/27 07:56:44 obrien Exp $
 */
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#include <stdio.h>
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#include <stdlib.h>
#include <unistd.h>
/* Use prototypes in function declarations. */
#define YY_USE_PROTOS
/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST
#else  /* ! __cplusplus */
#if __STDC__
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif /* __STDC__ */
#endif /* ! __cplusplus */
#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif
#ifdef YY_USE_CONST
#define Int_yyconst const
#else
#define Int_yyconst
#endif
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
/* Returned upon end-of-file. */
#define YY_NULL 0
/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN Int_yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((Int_yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Int_yyrestart( Int_yyin )
#define YY_END_OF_BUFFER_CHAR 0
/* Size of default input buffer. */
#define YY_BUF_SIZE 16384
typedef struct Int_yy_buffer_state *YY_BUFFER_STATE;
extern int Int_yyleng;
extern FILE *Int_yyin, *Int_yyout;
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *     if ( condition_holds )
 *         Int_yyless( 5 );
 *     else
 *         do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the Int_yyless() call.
 */
/* Return all but the first 'n' matched characters back to the input stream. */
#define Int_yyless(n) \
       do \
             { \
             /* Undo effects of setting up Int_yytext. */ \
             *Int_yy_cp = Int_yy_hold_char; \
             YY_RESTORE_YY_MORE_OFFSET \
             Int_yy_c_buf_p = Int_yy_cp = Int_yy_bp + n - YY_MORE_ADJ; \
             YY_DO_BEFORE_ACTION; /* set up Int_yytext again */ \
             } \
       while ( 0 )
#define unput(c) Int_yyunput( c, Int_yytext_ptr )
/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int Int_yy_size_t;
struct Int_yy_buffer_state {
       FILE *Int_yy_input_file;
       char *Int_yy_ch_buf;   /* input buffer */
       char *Int_yy_buf_pos;         /* current position in input buffer */
       /* Size of input buffer in bytes, not including room for EOB
        * characters.
        */
       Int_yy_size_t Int_yy_buf_size;
       /* Number of characters read into Int_yy_ch_buf, not including EOB
        * characters.
        */
       int Int_yy_n_chars;
       /* Whether we "own" the buffer - i.e., we know we created it,
        * and can realloc() it to grow it, and should free() it to
        * delete it.
        */
       int Int_yy_is_our_buffer;
       /* Whether this is an "interactive" input source; if so, and
        * if we're using stdio for input, then we want to use getc()
        * instead of fread(), to make sure we stop fetching input after
        * each newline.
        */
       int Int_yy_is_interactive;
       /* Whether we're considered to be at the beginning of a line.
        * If so, '^' rules will be active on the next match, otherwise
        * not.
        */
       int Int_yy_at_bol;
       /* Whether to try to fill the input buffer when we reach the
        * end of it.
        */
       int Int_yy_fill_buffer;
       int Int_yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
       /* When an EOF's been seen but there's still some text to process
        * then we mark the buffer as YY_EOF_PENDING, to indicate that we
        * shouldn't try reading from the input source any more.  We might
        * still have a bunch of tokens to match, though, because of
        * possible backing-up.
        *
        * When we actually see the EOF, we change the status to "new"
        * (via Int_yyrestart()), so that the user can continue scanning by
        * just pointing Int_yyin at a new input file.
        */
#define YY_BUFFER_EOF_PENDING 2
       };
static YY_BUFFER_STATE Int_yy_current_buffer = 0;
/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER Int_yy_current_buffer
/* Int_yy_hold_char holds the character lost when Int_yytext is formed. */
static char Int_yy_hold_char;
static int Int_yy_n_chars;         /* number of characters read into Int_yy_ch_buf */
int Int_yyleng;
/* Points to current character in buffer. */
static char *Int_yy_c_buf_p = (char *) 0;
static int Int_yy_init = 1;       /* whether we need to initialize */
static int Int_yy_start = 0;   /* start state number */
/* Flag which is used to allow Int_yywrap()'s to do buffer switches
 * instead of setting up a fresh Int_yyin.  A bit of a hack ...
 */
static int Int_yy_did_buffer_switch_on_eof;
void Int_yyrestart YY_PROTO(( FILE *input_file ));
void Int_yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void Int_yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE Int_yy_create_buffer YY_PROTO(( FILE *file, int size ));
void Int_yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void Int_yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void Int_yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER Int_yy_flush_buffer( Int_yy_current_buffer )
YY_BUFFER_STATE Int_yy_scan_buffer YY_PROTO(( char *base, Int_yy_size_t size ));
YY_BUFFER_STATE Int_yy_scan_string YY_PROTO(( Int_yyconst char *Int_yy_str ));
YY_BUFFER_STATE Int_yy_scan_bytes YY_PROTO(( Int_yyconst char *bytes, int len ));
static void *Int_yy_flex_alloc YY_PROTO(( Int_yy_size_t ));
static void *Int_yy_flex_realloc YY_PROTO(( void *, Int_yy_size_t ));
static void Int_yy_flex_free YY_PROTO(( void * ));
#define Int_yy_new_buffer Int_yy_create_buffer
#define Int_yy_set_interactive(is_interactive) \
       { \
       if ( ! Int_yy_current_buffer ) \
             Int_yy_current_buffer = Int_yy_create_buffer( Int_yyin, YY_BUF_SIZE ); \
       Int_yy_current_buffer->Int_yy_is_interactive = is_interactive; \
       }
#define Int_yy_set_bol(at_bol) \
       { \
       if ( ! Int_yy_current_buffer ) \
             Int_yy_current_buffer = Int_yy_create_buffer( Int_yyin, YY_BUF_SIZE ); \
       Int_yy_current_buffer->Int_yy_at_bol = at_bol; \
       }
#define YY_AT_BOL() (Int_yy_current_buffer->Int_yy_at_bol)
typedef unsigned char YY_CHAR;
FILE *Int_yyin = (FILE *) 0, *Int_yyout = (FILE *) 0;
typedef int Int_yy_state_type;
extern char *Int_yytext;
#define Int_yytext_ptr Int_yytext
static Int_yy_state_type Int_yy_get_previous_state YY_PROTO(( void ));
static Int_yy_state_type Int_yy_try_NUL_trans YY_PROTO(( Int_yy_state_type current_state ));
static int Int_yy_get_next_buffer YY_PROTO(( void ));
static void Int_yy_fatal_error YY_PROTO(( Int_yyconst char msg[] ));
/* Done after the current pattern has been matched and before the
 * corresponding action - sets up Int_yytext.
 */
#define YY_DO_BEFORE_ACTION \
       Int_yytext_ptr = Int_yy_bp; \
       Int_yyleng = (int) (Int_yy_cp - Int_yy_bp); \
       Int_yy_hold_char = *Int_yy_cp; \
       *Int_yy_cp = '\0'; \
       Int_yy_c_buf_p = Int_yy_cp;
#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
static Int_yyconst short int Int_yy_accept[132] =
    {   0,
        0,    0,   32,   30,   13,   12,   14,   30,   10,   11,
        8,   25,   30,   25,    9,   25,   25,   30,   25,   25,
       25,   25,   25,   25,   25,   25,   15,    0,   26,   25,
        0,   25,    0,   28,   27,   25,   25,   25,    0,   25,
        0,   25,   25,   25,   25,   25,   25,   25,   21,   25,
       25,   25,   25,   15,   25,    0,   27,    0,    0,   25,
       25,    0,   24,    4,    0,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,    0,   28,
        0,    0,   27,   29,   25,   25,   25,   25,   25,   25,
       25,   25,   25,    1,   25,   25,   25,    0,   27,   25,
       25,   17,    2,   25,   25,   20,   25,   25,   25,   22,
       25,    6,   25,    3,   25,   25,    7,   19,   25,   25,
       16,   18,   25,   25,   25,    5,   25,   25,   25,   23,
        0
    } ;
static Int_yyconst int Int_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    1,    9,   10,   11,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,    1,    1,
       14,    1,    1,    1,   15,   15,   15,   16,   17,   15,
       15,   15,   18,   15,   15,   15,   15,   15,   19,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       20,   21,   22,    1,   23,    1,   24,   25,   26,   27,
       28,   15,   29,   30,   31,   15,   15,   32,   15,   33,
       34,   35,   36,   37,   38,   39,   40,   15,   41,   42,
       15,   15,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;
static Int_yyconst int Int_yy_meta[43] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    1,    3,    3,    3,    3,    3,    4,
        3,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;
static Int_yyconst short int Int_yy_base[136] =
    {   0,
        0,  302,  287,  371,  371,  371,  371,  274,  371,  371,
      371,   31,  234,   42,  371,   36,   53,  222,   55,   57,
       47,   52,   49,   60,   65,   70,    0,  225,  371,   37,
      215,   94,  201,   33,   95,  101,   11,  108,  103,   56,
      175,   86,   90,   97,   93,  104,  113,  116,  100,  117,
      115,  127,  125,    0,  157,  162,  159,  168,  172,  170,
      150,  167,  371,  152,  161,  161,  160,  164,  168,  173,
      171,  181,  182,  184,  189,  186,  197,  220,  149,  147,
      225,  139,  123,   96,  208,  205,  217,  218,  215,  226,
      219,  230,  228,  229,  233,  242,  238,   89,   72,  251,
      241,  243,  250,  258,  259,  254,  261,  263,  272,  270,
      271,  273,  280,  275,  288,  285,  284,  287,  292,  305,
      296,  300,  310,  303,  301,  308,  315,  320,  318,  317,
      371,  360,   57,  362,  366
    } ;
static Int_yyconst short int Int_yy_def[136] =
    {   0,
      131,    1,  131,  131,  131,  131,  131,  132,  131,  131,
      131,  133,  131,  134,  131,  134,  134,  131,  134,  134,
       20,   20,   20,   20,   20,   20,  135,  132,  131,  133,
      131,  133,  131,  131,  131,   20,   20,   20,  131,   20,
      131,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,  135,  133,  131,  131,  131,  131,  133,
       20,  131,  131,   20,  131,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,  133,  131,  131,
      131,  131,  131,  131,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,  131,  131,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
        0,  131,  131,  131,  131
    } ;
static Int_yyconst short int Int_yy_nxt[414] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,    4,   11,
       12,   13,   14,   15,   16,   16,   16,   16,   17,    4,
       18,    4,   19,   16,   20,   21,   22,   16,   16,   16,
       23,   16,   16,   24,   16,   16,   16,   16,   16,   25,
       26,   16,   31,   32,   37,   34,   30,  131,  131,   56,
       37,   33,   30,   35,   36,   39,   33,   33,   38,   30,
       56,   39,   33,   30,  131,   30,  131,   30,  131,   38,
       40,   64,   39,   33,   39,   33,   39,   33,   45,   47,
       37,   48,   37,   46,   99,   37,   37,   42,   37,   37,
       43,   37,   49,   37,   50,   37,   44,   51,   37,   37,
       53,   99,   52,   37,   37,   35,   32,   57,   84,   37,
       55,   58,   35,   36,   33,   62,   59,   38,   60,   37,
       61,   55,   58,   67,   63,   66,   69,   68,   38,   37,
       37,   70,   37,   37,   37,   83,   37,   37,   71,   37,
       37,   37,   72,   37,   74,   75,   37,   37,   37,   37,
       37,   83,   37,   73,   37,   37,   37,   76,   37,   80,
       37,   80,   61,   77,   37,   59,   37,   60,  131,   78,
       79,   57,   79,   30,   80,   81,   82,   33,   82,   62,
       83,  131,   78,   37,   84,   37,   81,   65,   63,   37,
       33,   37,   85,   37,   37,   87,   89,   37,   86,   37,
       37,   37,   90,   37,   37,   88,   37,   37,   91,   93,
       37,   92,   37,   41,   37,   37,   94,   37,   96,   37,
       37,   37,   37,   37,   95,   37,   97,   34,   37,   29,
       37,  131,   78,   98,   41,   98,   37,   99,   37,  100,
       33,   37,  101,  102,   37,  103,   34,   37,   37,  105,
       37,   37,   37,  104,   37,  107,   37,   37,   37,   37,
      106,   37,   37,   37,  108,   37,   37,   37,   37,   37,
      110,  111,  109,  112,   37,   37,   37,   37,   29,  113,
       37,   37,   37,   37,   37,  114,  131,   37,  116,   37,
       37,   37,   37,   37,   37,  115,   37,   37,   37,  118,
       37,  117,   37,   37,   37,   37,   37,   27,   37,   37,
      119,   37,   37,   37,   37,  121,  120,   37,   37,   37,
       37,   37,  122,   37,   37,   37,   37,   37,  124,   37,
      123,   37,  125,   37,  127,   37,   37,  126,   37,   37,
       37,   37,   37,   37,   37,  128,  129,   37,   37,   37,
       37,   37,  131,   37,   37,  130,   37,   37,  131,   37,
       28,   28,   28,   28,   37,   37,   54,  131,   54,   54,
        3,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131
    } ;
static Int_yyconst short int Int_yy_chk[414] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   12,   12,   37,   34,   16,   16,   30,   34,
       37,   12,   14,   14,   14,   16,   16,   30,   14,  133,
       34,   14,   14,   17,   17,   19,   19,   20,   20,   14,
       17,   40,   17,   17,   19,   19,   20,   20,   21,   22,
       21,   23,   23,   21,   99,   22,   21,   19,   23,   40,
       20,   22,   24,   24,   24,   40,   20,   25,   25,   24,
       26,   98,   25,   26,   25,   32,   32,   35,   84,   26,
       32,   35,   36,   36,   32,   39,   38,   36,   38,   42,
       38,   32,   35,   43,   39,   42,   45,   44,   36,   43,
       44,   46,   45,   49,   36,   83,   44,   46,   47,   49,
       36,   38,   48,   46,   50,   51,   47,   38,   51,   48,
       50,   82,   47,   48,   51,   48,   50,   52,   53,   80,
       52,   79,   61,   53,   53,   55,   52,   55,   55,   55,
       56,   57,   56,   65,   56,   57,   58,   55,   58,   62,
       58,   60,   60,   61,   59,   64,   57,   41,   62,   61,
       60,   64,   66,   67,   66,   68,   70,   68,   67,   67,
       66,   69,   71,   68,   71,   69,   70,   69,   72,   73,
       71,   72,   70,   33,   72,   73,   74,   74,   76,   76,
       72,   73,   75,   74,   75,   76,   77,   31,   75,   28,
       77,   78,   78,   81,   18,   81,   77,   81,   86,   85,
       78,   85,   86,   87,   86,   88,   13,   85,   89,   90,
       87,   88,   91,   89,   89,   92,   87,   88,   91,   90,
       91,   93,   94,   92,   93,   90,   95,   93,   94,   92,
       96,   97,   95,  100,  101,   96,  102,   97,    8,  101,
      101,   96,  102,  103,  100,  104,    3,  106,  107,  103,
      100,  104,  105,  106,  107,  105,  108,  104,  105,  109,
      107,  108,  108,  110,  111,  109,  112,    2,  114,  110,
      111,  109,  112,  113,  114,  115,  113,  117,  116,  113,
      118,  115,  116,  117,  116,  119,  118,  115,  120,  121,
      119,  119,  123,  122,  125,  121,  124,  124,  120,  122,
      125,  126,  124,  123,  120,  127,  128,  126,  127,  123,
      130,  129,    0,  128,  127,  129,  130,  129,    0,  128,
      132,  132,  132,  132,  134,  134,  135,    0,  135,  135,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131
    } ;
static Int_yy_state_type Int_yy_last_accepting_state;
static char *Int_yy_last_accepting_cpos;
/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define Int_yymore() Int_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *Int_yytext;
#define INITIAL 0
/*-------------------------------------------------------------------------
 *
 * bootscanner.lex
 *       a lexical scanner for the bootstrap parser
 *
 * Portions Copyright (c) 1996-2001, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 *
 * IDENTIFICATION
 *       $Header: /cvsroot/pgsql/src/backend/bootstrap/bootscanner.l,v 1.21 2001/08/10 18:57:33 tgl Exp $
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"
#include <time.h>
#include "access/attnum.h"
#include "access/htup.h"
#include "access/itup.h"
#include "access/skey.h"
#include "access/strat.h"
#include "access/tupdesc.h"
#include "bootstrap/bootstrap.h"
#include "catalog/pg_am.h"
#include "catalog/pg_attribute.h"
#include "catalog/pg_class.h"
#include "nodes/nodes.h"
#include "nodes/parsenodes.h"
#include "nodes/pg_list.h"
#include "nodes/primnodes.h"
#include "parser/scansup.h"
#include "rewrite/prs2lock.h"
#include "storage/block.h"
#include "storage/fd.h"
#include "storage/itemptr.h"
#include "storage/off.h"
#include "utils/nabstime.h"
#include "utils/rel.h"
#include "bootstrap_tokens.h"
#define                     YY_NO_UNPUT
/* some versions of lex define this as a macro */
#if defined(Int_yywrap)
#undef Int_yywrap
#endif /* Int_yywrap */
YYSTYPE Int_yylval;
int       Int_yyline;  /* keep track of the line number for error reporting */
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */
#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Int_yywrap YY_PROTO(( void ));
#else
extern int Int_yywrap YY_PROTO(( void ));
#endif
#endif
#ifndef YY_NO_UNPUT
static void Int_yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif
#ifndef Int_yytext_ptr
static void Int_yy_flex_strncpy YY_PROTO(( char *, Int_yyconst char *, int ));
#endif
#ifdef YY_NEED_STRLEN
static int Int_yy_flex_strlen YY_PROTO(( Int_yyconst char * ));
#endif
#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int Int_yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif
#if YY_STACK_USED
static int Int_yy_start_stack_ptr = 0;
static int Int_yy_start_stack_depth = 0;
static int *Int_yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void Int_yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void Int_yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int Int_yy_top_state YY_PROTO(( void ));
#endif
#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif
#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( Int_yytext, Int_yyleng, 1, Int_yyout )
#endif
/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
       if ( Int_yy_current_buffer->Int_yy_is_interactive ) \
             { \
             int c = '*', n; \
             for ( n = 0; n < max_size && \
                       (c = getc( Int_yyin )) != EOF && c != '\n'; ++n ) \
                  buf[n] = (char) c; \
             if ( c == '\n' ) \
                  buf[n++] = (char) c; \
             if ( c == EOF && ferror( Int_yyin ) ) \
                  YY_FATAL_ERROR( "input in flex scanner failed" ); \
             result = n; \
             } \
       else if ( ((result = fread( buf, 1, max_size, Int_yyin )) == 0) \
               && ferror( Int_yyin ) ) \
             YY_FATAL_ERROR( "input in flex scanner failed" );
#endif
/* No semi-colon after return; correct usage is to write "Int_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef Int_yyterminate
#define Int_yyterminate() return YY_NULL
#endif
/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif
/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) Int_yy_fatal_error( msg )
#endif
/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int Int_yylex YY_PROTO(( void ))
#endif
/* Code executed at the beginning of each rule, after Int_yytext and Int_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif
/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif
#define YY_RULE_SETUP \
       if ( Int_yyleng > 0 ) \
             Int_yy_current_buffer->Int_yy_at_bol = \
                      (Int_yytext[Int_yyleng - 1] == '\n'); \
       YY_USER_ACTION
YY_DECL {
       register Int_yy_state_type Int_yy_current_state;
       register char *Int_yy_cp, *Int_yy_bp;
       register int Int_yy_act;
       if ( Int_yy_init ) {
             Int_yy_init = 0;
#ifdef YY_USER_INIT
             YY_USER_INIT;
#endif
             if ( ! Int_yy_start )
                  Int_yy_start = 1;   /* first start state */
             if ( ! Int_yyin )
                  Int_yyin = stdin;
             if ( ! Int_yyout )
                  Int_yyout = stdout;
             if ( ! Int_yy_current_buffer )
                  Int_yy_current_buffer =
                      Int_yy_create_buffer( Int_yyin, YY_BUF_SIZE );
             Int_yy_load_buffer_state(); }
       while ( 1 )     /* loops until end-of-file is reached */ {
             Int_yy_cp = Int_yy_c_buf_p;
             /* Support of Int_yytext. */
             *Int_yy_cp = Int_yy_hold_char;
             /* Int_yy_bp points to the position in Int_yy_ch_buf of the start of
              * the current run.
              */
             Int_yy_bp = Int_yy_cp;
             Int_yy_current_state = Int_yy_start;
             Int_yy_current_state += YY_AT_BOL();
Int_yy_match:
             do {
                  register YY_CHAR Int_yy_c = Int_yy_ec[YY_SC_TO_UI(*Int_yy_cp)];
                  if ( Int_yy_accept[Int_yy_current_state] ) {
                      Int_yy_last_accepting_state = Int_yy_current_state;
                      Int_yy_last_accepting_cpos = Int_yy_cp; }
                  while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state ) {
                      Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
                      if ( Int_yy_current_state >= 132 )
                         Int_yy_c = Int_yy_meta[(unsigned int) Int_yy_c]; }
                  Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + (unsigned int) Int_yy_c];
                  ++Int_yy_cp; }
             while ( Int_yy_base[Int_yy_current_state] != 371 );
Int_yy_find_action:
             Int_yy_act = Int_yy_accept[Int_yy_current_state];
             if ( Int_yy_act == 0 )
                  { /* have to back up */
                  Int_yy_cp = Int_yy_last_accepting_cpos;
                  Int_yy_current_state = Int_yy_last_accepting_state;
                  Int_yy_act = Int_yy_accept[Int_yy_current_state]; }
             YY_DO_BEFORE_ACTION;
do_action:     /* This label is used only to access EOF actions. */
             switch ( Int_yy_act )
       { /* beginning of action switch */
                  case 0: /* must back up */
                  /* undo the effects of YY_DO_BEFORE_ACTION */
                  *Int_yy_cp = Int_yy_hold_char;
                  Int_yy_cp = Int_yy_last_accepting_cpos;
                  Int_yy_current_state = Int_yy_last_accepting_state;
                  goto Int_yy_find_action;
case 1:
YY_RULE_SETUP
{ return(OPEN); }
       YY_BREAK
case 2:
YY_RULE_SETUP
{ return(XCLOSE); }
       YY_BREAK
case 3:
YY_RULE_SETUP
{ return(XCREATE); }
       YY_BREAK
case 4:
YY_RULE_SETUP
{ return(OBJ_ID); }
       YY_BREAK
case 5:
YY_RULE_SETUP
{ return(XBOOTSTRAP); }
       YY_BREAK
case 6:
YY_RULE_SETUP
{ return(NULLVAL); }
       YY_BREAK
case 7:
YY_RULE_SETUP
{ return(INSERT_TUPLE); }
       YY_BREAK
case 8:
YY_RULE_SETUP
{ return(COMMA); }
       YY_BREAK
case 9:
YY_RULE_SETUP
{ return(EQUALS); }
       YY_BREAK
case 10:
YY_RULE_SETUP
{ return(LPAREN); }
       YY_BREAK
case 11:
YY_RULE_SETUP
{ return(RPAREN); }
       YY_BREAK
case 12:
YY_RULE_SETUP
{ Int_yyline++; }
       YY_BREAK
case 13:
YY_RULE_SETUP
;
       YY_BREAK
case 14:
YY_RULE_SETUP
;
       YY_BREAK
case 15:
YY_RULE_SETUP
; /* drop everything after "#" for comments */
       YY_BREAK
case 16:
YY_RULE_SETUP
{ return(XDECLARE); }
       YY_BREAK
case 17:
YY_RULE_SETUP
{ return(XBUILD); }
       YY_BREAK
case 18:
YY_RULE_SETUP
{ return(INDICES); }
       YY_BREAK
case 19:
YY_RULE_SETUP
{ return(UNIQUE); }
       YY_BREAK
case 20:
YY_RULE_SETUP
{ return(INDEX); }
       YY_BREAK
case 21:
YY_RULE_SETUP
{ return(ON); }
       YY_BREAK
case 22:
YY_RULE_SETUP
{ return(USING); }
       YY_BREAK
case 23:
YY_RULE_SETUP
{ return(XWITHOUT_OIDS); }
       YY_BREAK
case 24:
YY_RULE_SETUP {
                         Int_yylval.ival = EnterString(MapArrayTypeName((char*)Int_yytext));
                         return(ID); }
       YY_BREAK
case 25:
YY_RULE_SETUP {
                         char   *newid = scanstr((char*)Int_yytext);
                         Int_yylval.ival = EnterString(newid);
                         pfree(newid);
                         return(ID); }
       YY_BREAK
case 26:
YY_RULE_SETUP {
                         char   *newid;
                         Int_yytext[strlen(Int_yytext)-1] = '\0'; /* strip off quotes */
                         newid = scanstr((char*)Int_yytext+1);
                         Int_yylval.ival = EnterString(newid);
                         pfree(newid);
                         Int_yytext[strlen(Int_yytext)] = '"'; /* restore quotes */
                         return(ID); }
       YY_BREAK
case 27:
case 28:
case 29:
YY_RULE_SETUP {
                            Int_yylval.ival = EnterString((char*)Int_yytext);
                            return(CONST); }
       YY_BREAK
case 30:
YY_RULE_SETUP {
                         elog(ERROR, "syntax error at line %d: unexpected character %s", Int_yyline, Int_yytext); }
       YY_BREAK
case 31:
YY_RULE_SETUP
ECHO;
       YY_BREAK
case YY_STATE_EOF(INITIAL):
       Int_yyterminate();
       case YY_END_OF_BUFFER: {
             /* Amount of text matched not including the EOB char. */
             int Int_yy_amount_of_matched_text = (int) (Int_yy_cp - Int_yytext_ptr) - 1;
             /* Undo the effects of YY_DO_BEFORE_ACTION. */
             *Int_yy_cp = Int_yy_hold_char;
             YY_RESTORE_YY_MORE_OFFSET
             if ( Int_yy_current_buffer->Int_yy_buffer_status == YY_BUFFER_NEW ) {
                  /* We're scanning a new file or input source.  It's
                   * possible that this happened because the user
                   * just pointed Int_yyin at a new source and called
                   * Int_yylex().  If so, then we have to assure
                   * consistency between Int_yy_current_buffer and our
                   * globals.  Here is the right place to do so, because
                   * this is the first action (other than possibly a
                   * back-up) that will match for the new input source.
                   */
                  Int_yy_n_chars = Int_yy_current_buffer->Int_yy_n_chars;
                  Int_yy_current_buffer->Int_yy_input_file = Int_yyin;
                  Int_yy_current_buffer->Int_yy_buffer_status = YY_BUFFER_NORMAL; }
             /* Note that here we test for Int_yy_c_buf_p "<=" to the position
              * of the first EOB in the buffer, since Int_yy_c_buf_p will
              * already have been incremented past the NUL character
              * (since all states make transitions on EOB to the
              * end-of-buffer state).  Contrast this with the test
              * in input().
              */
             if ( Int_yy_c_buf_p <= &Int_yy_current_buffer->Int_yy_ch_buf[Int_yy_n_chars] )
                  { /* This was really a NUL. */
                  Int_yy_state_type Int_yy_next_state;
                  Int_yy_c_buf_p = Int_yytext_ptr + Int_yy_amount_of_matched_text;
                  Int_yy_current_state = Int_yy_get_previous_state();
                  /* Okay, we're now positioned to make the NUL
                   * transition.  We couldn't have
                   * Int_yy_get_previous_state() go ahead and do it
                   * for us because it doesn't know how to deal
                   * with the possibility of jamming (and we don't
                   * want to build jamming into it because then it
                   * will run more slowly).
                   */
                  Int_yy_next_state = Int_yy_try_NUL_trans( Int_yy_current_state );
                  Int_yy_bp = Int_yytext_ptr + YY_MORE_ADJ;
                  if ( Int_yy_next_state ) {
                      /* Consume the NUL. */
                      Int_yy_cp = ++Int_yy_c_buf_p;
                      Int_yy_current_state = Int_yy_next_state;
                      goto Int_yy_match; }
                  else {
                      Int_yy_cp = Int_yy_c_buf_p;
                      goto Int_yy_find_action; } }
             else switch ( Int_yy_get_next_buffer() ) {
                  case EOB_ACT_END_OF_FILE: {
                      Int_yy_did_buffer_switch_on_eof = 0;
                      if ( Int_yywrap() ) {
                         /* Note: because we've taken care in
                          * Int_yy_get_next_buffer() to have set up
                          * Int_yytext, we can now set up
                          * Int_yy_c_buf_p so that if some total
                          * hoser (like flex itself) wants to
                          * call the scanner after we return the
                          * YY_NULL, it'll still work - another
                          * YY_NULL will get returned.
                          */
                         Int_yy_c_buf_p = Int_yytext_ptr + YY_MORE_ADJ;
                         Int_yy_act = YY_STATE_EOF(YY_START);
                         goto do_action; }
                      else {
                         if ( ! Int_yy_did_buffer_switch_on_eof )
                           YY_NEW_FILE; }
                      break; }
                  case EOB_ACT_CONTINUE_SCAN:
                      Int_yy_c_buf_p =
                         Int_yytext_ptr + Int_yy_amount_of_matched_text;
                      Int_yy_current_state = Int_yy_get_previous_state();
                      Int_yy_cp = Int_yy_c_buf_p;
                      Int_yy_bp = Int_yytext_ptr + YY_MORE_ADJ;
                      goto Int_yy_match;
                  case EOB_ACT_LAST_MATCH:
                      Int_yy_c_buf_p =
                      &Int_yy_current_buffer->Int_yy_ch_buf[Int_yy_n_chars];
                      Int_yy_current_state = Int_yy_get_previous_state();
                      Int_yy_cp = Int_yy_c_buf_p;
                      Int_yy_bp = Int_yytext_ptr + YY_MORE_ADJ;
                      goto Int_yy_find_action; }
             break; }
       default:
             YY_FATAL_ERROR(
                  "fatal flex scanner internal error--no action found" );
       } /* end of action switch */
             } /* end of scanning one token */
       } /* end of Int_yylex */
/* Int_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *     EOB_ACT_LAST_MATCH -
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
static int Int_yy_get_next_buffer() {
       register char *dest = Int_yy_current_buffer->Int_yy_ch_buf;
       register char *source = Int_yytext_ptr;
       register int number_to_move, i;
       int ret_val;
       if ( Int_yy_c_buf_p > &Int_yy_current_buffer->Int_yy_ch_buf[Int_yy_n_chars + 1] )
             YY_FATAL_ERROR(
             "fatal flex scanner internal error--end of buffer missed" );
       if ( Int_yy_current_buffer->Int_yy_fill_buffer == 0 )
             { /* Don't try to fill the buffer, so this is an EOF. */
             if ( Int_yy_c_buf_p - Int_yytext_ptr - YY_MORE_ADJ == 1 ) {
                  /* We matched a single character, the EOB, so
                   * treat this as a final EOF.
                   */
                  return EOB_ACT_END_OF_FILE; }
             else {
                  /* We matched some text prior to the EOB, first
                   * process it.
                   */
                  return EOB_ACT_LAST_MATCH; } }
       /* Try to read more data. */
       /* First move last chars to start of buffer. */
       number_to_move = (int) (Int_yy_c_buf_p - Int_yytext_ptr) - 1;
       for ( i = 0; i < number_to_move; ++i )
             *(dest++) = *(source++);
       if ( Int_yy_current_buffer->Int_yy_buffer_status == YY_BUFFER_EOF_PENDING )
             /* don't do the read, it's not guaranteed to return an EOF,
              * just force an EOF
              */
             Int_yy_current_buffer->Int_yy_n_chars = Int_yy_n_chars = 0;
       else {
             int num_to_read =
                  Int_yy_current_buffer->Int_yy_buf_size - number_to_move - 1;
             while ( num_to_read <= 0 )
                  { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
                  YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else
                  /* just a shorter name for the current buffer */
                  YY_BUFFER_STATE b = Int_yy_current_buffer;
                  int Int_yy_c_buf_p_offset =
                      (int) (Int_yy_c_buf_p - b->Int_yy_ch_buf);
                  if ( b->Int_yy_is_our_buffer ) {
                      int new_size = b->Int_yy_buf_size * 2;
                      if ( new_size <= 0 )
                         b->Int_yy_buf_size += b->Int_yy_buf_size / 8;
                      else
                         b->Int_yy_buf_size *= 2;
                      b->Int_yy_ch_buf = (char *)
                         /* Include room in for 2 EOB chars. */
                         Int_yy_flex_realloc( (void *) b->Int_yy_ch_buf,
                             b->Int_yy_buf_size + 2 ); }
                  else
                      /* Can't grow it, we don't own it. */
                      b->Int_yy_ch_buf = 0;
                  if ( ! b->Int_yy_ch_buf )
                      YY_FATAL_ERROR(
                      "fatal error - scanner input buffer overflow" );
                  Int_yy_c_buf_p = &b->Int_yy_ch_buf[Int_yy_c_buf_p_offset];
                  num_to_read = Int_yy_current_buffer->Int_yy_buf_size -
                           number_to_move - 1;
#endif
                  }
             if ( num_to_read > YY_READ_BUF_SIZE )
                  num_to_read = YY_READ_BUF_SIZE;
             /* Read in more data. */
             YY_INPUT( (&Int_yy_current_buffer->Int_yy_ch_buf[number_to_move]),
                  Int_yy_n_chars, num_to_read );
             Int_yy_current_buffer->Int_yy_n_chars = Int_yy_n_chars; }
       if ( Int_yy_n_chars == 0 ) {
             if ( number_to_move == YY_MORE_ADJ ) {
                  ret_val = EOB_ACT_END_OF_FILE;
                  Int_yyrestart( Int_yyin ); }
             else {
                  ret_val = EOB_ACT_LAST_MATCH;
                  Int_yy_current_buffer->Int_yy_buffer_status =
                      YY_BUFFER_EOF_PENDING; } }
       else
             ret_val = EOB_ACT_CONTINUE_SCAN;
       Int_yy_n_chars += number_to_move;
       Int_yy_current_buffer->Int_yy_ch_buf[Int_yy_n_chars] = YY_END_OF_BUFFER_CHAR;
       Int_yy_current_buffer->Int_yy_ch_buf[Int_yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
       Int_yytext_ptr = &Int_yy_current_buffer->Int_yy_ch_buf[0];
       return ret_val; }
/* Int_yy_get_previous_state - get the state just before the EOB char was reached */
static Int_yy_state_type Int_yy_get_previous_state() {
       register Int_yy_state_type Int_yy_current_state;
       register char *Int_yy_cp;
       Int_yy_current_state = Int_yy_start;
       Int_yy_current_state += YY_AT_BOL();
       for ( Int_yy_cp = Int_yytext_ptr + YY_MORE_ADJ; Int_yy_cp < Int_yy_c_buf_p; ++Int_yy_cp ) {
             register YY_CHAR Int_yy_c = (*Int_yy_cp ? Int_yy_ec[YY_SC_TO_UI(*Int_yy_cp)] : 1);
             if ( Int_yy_accept[Int_yy_current_state] ) {
                  Int_yy_last_accepting_state = Int_yy_current_state;
                  Int_yy_last_accepting_cpos = Int_yy_cp; }
             while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state ) {
                  Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
                  if ( Int_yy_current_state >= 132 )
                      Int_yy_c = Int_yy_meta[(unsigned int) Int_yy_c]; }
             Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + (unsigned int) Int_yy_c]; }
       return Int_yy_current_state; }
/* Int_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = Int_yy_try_NUL_trans( current_state );
 */
#ifdef YY_USE_PROTOS
static Int_yy_state_type Int_yy_try_NUL_trans( Int_yy_state_type Int_yy_current_state )
#else
static Int_yy_state_type Int_yy_try_NUL_trans( Int_yy_current_state )
Int_yy_state_type Int_yy_current_state;
#endif
       {
       register int Int_yy_is_jam;
       register char *Int_yy_cp = Int_yy_c_buf_p;
       register YY_CHAR Int_yy_c = 1;
       if ( Int_yy_accept[Int_yy_current_state] ) {
             Int_yy_last_accepting_state = Int_yy_current_state;
             Int_yy_last_accepting_cpos = Int_yy_cp; }
       while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state ) {
             Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
             if ( Int_yy_current_state >= 132 )
                  Int_yy_c = Int_yy_meta[(unsigned int) Int_yy_c]; }
       Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + (unsigned int) Int_yy_c];
       Int_yy_is_jam = (Int_yy_current_state == 131);
       return Int_yy_is_jam ? 0 : Int_yy_current_state; }
#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void Int_yyunput( int c, register char *Int_yy_bp )
#else
static void Int_yyunput( c, Int_yy_bp )
int c;
register char *Int_yy_bp;
#endif
       {
       register char *Int_yy_cp = Int_yy_c_buf_p;
       /* undo effects of setting up Int_yytext */
       *Int_yy_cp = Int_yy_hold_char;
       if ( Int_yy_cp < Int_yy_current_buffer->Int_yy_ch_buf + 2 )
             { /* need to shift things up to make room */
             /* +2 for EOB chars. */
             register int number_to_move = Int_yy_n_chars + 2;
             register char *dest = &Int_yy_current_buffer->Int_yy_ch_buf[
                         Int_yy_current_buffer->Int_yy_buf_size + 2];
             register char *source =
                      &Int_yy_current_buffer->Int_yy_ch_buf[number_to_move];
             while ( source > Int_yy_current_buffer->Int_yy_ch_buf )
                  *--dest = *--source;
             Int_yy_cp += (int) (dest - source);
             Int_yy_bp += (int) (dest - source);
             Int_yy_current_buffer->Int_yy_n_chars =
                  Int_yy_n_chars = Int_yy_current_buffer->Int_yy_buf_size;
             if ( Int_yy_cp < Int_yy_current_buffer->Int_yy_ch_buf + 2 )
                  YY_FATAL_ERROR( "flex scanner push-back overflow" ); }
       *--Int_yy_cp = (char) c;
       Int_yytext_ptr = Int_yy_bp;
       Int_yy_hold_char = *Int_yy_cp;
       Int_yy_c_buf_p = Int_yy_cp; }
#endif /* ifndef YY_NO_UNPUT */
#ifdef __cplusplus
static int Int_yyinput()
#else
static int input()
#endif
       {
       int c;
       *Int_yy_c_buf_p = Int_yy_hold_char;
       if ( *Int_yy_c_buf_p == YY_END_OF_BUFFER_CHAR ) {
             /* Int_yy_c_buf_p now points to the character we want to return.
              * If this occurs *before* the EOB characters, then it's a
              * valid NUL; if not, then we've hit the end of the buffer.
              */
             if ( Int_yy_c_buf_p < &Int_yy_current_buffer->Int_yy_ch_buf[Int_yy_n_chars] )
                  /* This was really a NUL. */
                  *Int_yy_c_buf_p = '\0';
             else
                  { /* need more input */
                  int offset = Int_yy_c_buf_p - Int_yytext_ptr;
                  ++Int_yy_c_buf_p;
                  switch ( Int_yy_get_next_buffer() ) {
                      case EOB_ACT_LAST_MATCH:
                         /* This happens because Int_yy_g_n_b()
                          * sees that we've accumulated a
                          * token and flags that we need to
                          * try matching the token before
                          * proceeding.  But for input(),
                          * there's no matching to consider.
                          * So convert the EOB_ACT_LAST_MATCH
                          * to EOB_ACT_END_OF_FILE.
                          */
                         /* Reset buffer status. */
                         Int_yyrestart( Int_yyin );
                         /* fall through */
                      case EOB_ACT_END_OF_FILE: {
                         if ( Int_yywrap() )
                           return EOF;
                         if ( ! Int_yy_did_buffer_switch_on_eof )
                           YY_NEW_FILE;
#ifdef __cplusplus
                         return Int_yyinput();
#else
                         return input();
#endif
                         }
                      case EOB_ACT_CONTINUE_SCAN:
                         Int_yy_c_buf_p = Int_yytext_ptr + offset;
                         break; } } }
       c = *(unsigned char *) Int_yy_c_buf_p;        /* cast for 8-bit char's */
       *Int_yy_c_buf_p = '\0';       /* preserve Int_yytext */
       Int_yy_hold_char = *++Int_yy_c_buf_p;
       Int_yy_current_buffer->Int_yy_at_bol = (c == '\n');
       return c; }
#ifdef YY_USE_PROTOS
void Int_yyrestart( FILE *input_file )
#else
void Int_yyrestart( input_file )
FILE *input_file;
#endif
       {
       if ( ! Int_yy_current_buffer )
             Int_yy_current_buffer = Int_yy_create_buffer( Int_yyin, YY_BUF_SIZE );
       Int_yy_init_buffer( Int_yy_current_buffer, input_file );
       Int_yy_load_buffer_state(); }
#ifdef YY_USE_PROTOS
void Int_yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void Int_yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
       {
       if ( Int_yy_current_buffer == new_buffer )
             return;
       if ( Int_yy_current_buffer ) {
             /* Flush out information for old buffer. */
             *Int_yy_c_buf_p = Int_yy_hold_char;
             Int_yy_current_buffer->Int_yy_buf_pos = Int_yy_c_buf_p;
             Int_yy_current_buffer->Int_yy_n_chars = Int_yy_n_chars; }
       Int_yy_current_buffer = new_buffer;
       Int_yy_load_buffer_state();
       /* We don't actually know whether we did this switch during
        * EOF (Int_yywrap()) processing, but the only time this flag
        * is looked at is after Int_yywrap() is called, so it's safe
        * to go ahead and always set it.
        */
       Int_yy_did_buffer_switch_on_eof = 1; }
#ifdef YY_USE_PROTOS
void Int_yy_load_buffer_state( void )
#else
void Int_yy_load_buffer_state()
#endif
       {
       Int_yy_n_chars = Int_yy_current_buffer->Int_yy_n_chars;
       Int_yytext_ptr = Int_yy_c_buf_p = Int_yy_current_buffer->Int_yy_buf_pos;
       Int_yyin = Int_yy_current_buffer->Int_yy_input_file;
       Int_yy_hold_char = *Int_yy_c_buf_p; }
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE Int_yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE Int_yy_create_buffer( file, size )
FILE *file;
int size;
#endif
       {
       YY_BUFFER_STATE b;
       b = (YY_BUFFER_STATE) Int_yy_flex_alloc( sizeof( struct Int_yy_buffer_state ) );
       if ( ! b )
             YY_FATAL_ERROR( "out of dynamic memory in Int_yy_create_buffer()" );
       b->Int_yy_buf_size = size;
       /* Int_yy_ch_buf has to be 2 characters longer than the size given because
        * we need to put in 2 end-of-buffer characters.
        */
       b->Int_yy_ch_buf = (char *) Int_yy_flex_alloc( b->Int_yy_buf_size + 2 );
       if ( ! b->Int_yy_ch_buf )
             YY_FATAL_ERROR( "out of dynamic memory in Int_yy_create_buffer()" );
       b->Int_yy_is_our_buffer = 1;
       Int_yy_init_buffer( b, file );
       return b; }
#ifdef YY_USE_PROTOS
void Int_yy_delete_buffer( YY_BUFFER_STATE b )
#else
void Int_yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
       {
       if ( ! b )
             return;
       if ( b == Int_yy_current_buffer )
             Int_yy_current_buffer = (YY_BUFFER_STATE) 0;
       if ( b->Int_yy_is_our_buffer )
             Int_yy_flex_free( (void *) b->Int_yy_ch_buf );
       Int_yy_flex_free( (void *) b ); }
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#ifdef YY_USE_PROTOS
void Int_yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void Int_yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
       {
       Int_yy_flush_buffer( b );
       b->Int_yy_input_file = file;
       b->Int_yy_fill_buffer = 1;
#if YY_ALWAYS_INTERACTIVE
       b->Int_yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
       b->Int_yy_is_interactive = 0;
#else
       b->Int_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
       }
#ifdef YY_USE_PROTOS
void Int_yy_flush_buffer( YY_BUFFER_STATE b )
#else
void Int_yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif
       {
       if ( ! b )
             return;
       b->Int_yy_n_chars = 0;
       /* We always need two end-of-buffer characters.  The first causes
        * a transition to the end-of-buffer state.  The second causes
        * a jam in that state.
        */
       b->Int_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
       b->Int_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
       b->Int_yy_buf_pos = &b->Int_yy_ch_buf[0];
       b->Int_yy_at_bol = 1;
       b->Int_yy_buffer_status = YY_BUFFER_NEW;
       if ( b == Int_yy_current_buffer )
             Int_yy_load_buffer_state(); }
#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE Int_yy_scan_buffer( char *base, Int_yy_size_t size )
#else
YY_BUFFER_STATE Int_yy_scan_buffer( base, size )
char *base;
Int_yy_size_t size;
#endif
       {
       YY_BUFFER_STATE b;
       if ( size < 2 ||
            base[size-2] != YY_END_OF_BUFFER_CHAR ||
            base[size-1] != YY_END_OF_BUFFER_CHAR )
             /* They forgot to leave room for the EOB's. */
             return 0;
       b = (YY_BUFFER_STATE) Int_yy_flex_alloc( sizeof( struct Int_yy_buffer_state ) );
       if ( ! b )
             YY_FATAL_ERROR( "out of dynamic memory in Int_yy_scan_buffer()" );
       b->Int_yy_buf_size = size - 2;        /* "- 2" to take care of EOB's */
       b->Int_yy_buf_pos = b->Int_yy_ch_buf = base;
       b->Int_yy_is_our_buffer = 0;
       b->Int_yy_input_file = 0;
       b->Int_yy_n_chars = b->Int_yy_buf_size;
       b->Int_yy_is_interactive = 0;
       b->Int_yy_at_bol = 1;
       b->Int_yy_fill_buffer = 0;
       b->Int_yy_buffer_status = YY_BUFFER_NEW;
       Int_yy_switch_to_buffer( b );
       return b; }
#endif
#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE Int_yy_scan_string( Int_yyconst char *Int_yy_str )
#else
YY_BUFFER_STATE Int_yy_scan_string( Int_yy_str )
Int_yyconst char *Int_yy_str;
#endif
       {
       int len;
       for ( len = 0; Int_yy_str[len]; ++len )
             ;
       return Int_yy_scan_bytes( Int_yy_str, len ); }
#endif
#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE Int_yy_scan_bytes( Int_yyconst char *bytes, int len )
#else
YY_BUFFER_STATE Int_yy_scan_bytes( bytes, len )
Int_yyconst char *bytes;
int len;
#endif
       {
       YY_BUFFER_STATE b;
       char *buf;
       Int_yy_size_t n;
       int i;
       /* Get memory for full buffer, including space for trailing EOB's. */
       n = len + 2;
       buf = (char *) Int_yy_flex_alloc( n );
       if ( ! buf )
             YY_FATAL_ERROR( "out of dynamic memory in Int_yy_scan_bytes()" );
       for ( i = 0; i < len; ++i )
             buf[i] = bytes[i];
       buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;
       b = Int_yy_scan_buffer( buf, n );
       if ( ! b )
             YY_FATAL_ERROR( "bad buffer in Int_yy_scan_bytes()" );
       /* It's okay to grow etc. this buffer, and we should throw it
        * away when we're done.
        */
       b->Int_yy_is_our_buffer = 1;
       return b; }
#endif
#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void Int_yy_push_state( int new_state )
#else
static void Int_yy_push_state( new_state )
int new_state;
#endif
       {
       if ( Int_yy_start_stack_ptr >= Int_yy_start_stack_depth ) {
             Int_yy_size_t new_size;
             Int_yy_start_stack_depth += YY_START_STACK_INCR;
             new_size = Int_yy_start_stack_depth * sizeof( int );
             if ( ! Int_yy_start_stack )
                  Int_yy_start_stack = (int *) Int_yy_flex_alloc( new_size );
             else
                  Int_yy_start_stack = (int *) Int_yy_flex_realloc(
                         (void *) Int_yy_start_stack, new_size );
             if ( ! Int_yy_start_stack )
                  YY_FATAL_ERROR(
                  "out of memory expanding start-condition stack" ); }
       Int_yy_start_stack[Int_yy_start_stack_ptr++] = YY_START;
       BEGIN(new_state); }
#endif
#ifndef YY_NO_POP_STATE
static void Int_yy_pop_state() {
       if ( --Int_yy_start_stack_ptr < 0 )
             YY_FATAL_ERROR( "start-condition stack underflow" );
       BEGIN(Int_yy_start_stack[Int_yy_start_stack_ptr]); }
#endif
#ifndef YY_NO_TOP_STATE
static int Int_yy_top_state() {
       return Int_yy_start_stack[Int_yy_start_stack_ptr - 1]; }
#endif
#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif
#ifdef YY_USE_PROTOS
static void Int_yy_fatal_error( Int_yyconst char msg[] )
#else
static void Int_yy_fatal_error( msg )
char msg[];
#endif
       {
       (void) fprintf( stderr, "%s\n", msg );
       exit( YY_EXIT_FAILURE ); }
/* Redefine Int_yyless() so it works in section 3 code. */
#undef Int_yyless
#define Int_yyless(n) \
       do \
             { \
             /* Undo effects of setting up Int_yytext. */ \
             Int_yytext[Int_yyleng] = Int_yy_hold_char; \
             Int_yy_c_buf_p = Int_yytext + n; \
             Int_yy_hold_char = *Int_yy_c_buf_p; \
             *Int_yy_c_buf_p = '\0'; \
             Int_yyleng = n; \
             } \
       while ( 0 )
/* Internal utility routines. */
#ifndef Int_yytext_ptr
#ifdef YY_USE_PROTOS
static void Int_yy_flex_strncpy( char *s1, Int_yyconst char *s2, int n )
#else
static void Int_yy_flex_strncpy( s1, s2, n )
char *s1;
Int_yyconst char *s2;
int n;
#endif
       {
       register int i;
       for ( i = 0; i < n; ++i )
             s1[i] = s2[i]; }
#endif
#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int Int_yy_flex_strlen( Int_yyconst char *s )
#else
static int Int_yy_flex_strlen( s )
Int_yyconst char *s;
#endif
       {
       register int n;
       for ( n = 0; s[n]; ++n )
             ;
       return n; }
#endif
#ifdef YY_USE_PROTOS
static void *Int_yy_flex_alloc( Int_yy_size_t size )
#else
static void *Int_yy_flex_alloc( size )
Int_yy_size_t size;
#endif
       {
       return (void *) malloc( size ); }
#ifdef YY_USE_PROTOS
static void *Int_yy_flex_realloc( void *ptr, Int_yy_size_t size )
#else
static void *Int_yy_flex_realloc( ptr, size )
void *ptr;
Int_yy_size_t size;
#endif
       {
       /* The cast to (char *) in the following accommodates both
        * implementations that use char* generic pointers, and those
        * that use void* generic pointers.  It works with the latter
        * because both ANSI C and C++ allow castless assignment from
        * any pointer type to void*, and deal with argument conversions
        * as though doing an assignment.
        */
       return (void *) realloc( (char *) ptr, size ); }
#ifdef YY_USE_PROTOS
static void Int_yy_flex_free( void *ptr )
#else
static void Int_yy_flex_free( ptr )
void *ptr;
#endif
       {
       free( ptr ); }
#if YY_MAIN
int main() {
       Int_yylex();
       return 0; }
#endif
int
Int_yywrap(void) {
       return 1; }
void
Int_yyerror(const char *str) {
       elog(ERROR, "syntax error at line %d: unexpected token %s", Int_yyline, str); }
