using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("Castle.DynamicProxy for Microsoft .NET Framework 2.0")]
[assembly: AssemblyDescriptionAttribute("Dynamic Proxy Generator for the CLR")]
[assembly: AssemblyCompanyAttribute("Castle Project")]
[assembly: AssemblyProductAttribute("Castle.DynamicProxy")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2004,2005 Castle Project - http://www.castleproject.org")]
[assembly: AssemblyVersionAttribute("1.1.5.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.5.4333")]
[assembly: AssemblyFileVersionAttribute("1.1.5.4333")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]

