#define yy_create_buffer base_yy_create_buffer
#define yy_delete_buffer base_yy_delete_buffer
#define yy_scan_buffer base_yy_scan_buffer
#define yy_scan_string base_yy_scan_string
#define yy_scan_bytes base_yy_scan_bytes
#define yy_flex_debug base_yy_flex_debug
#define yy_init_buffer base_yy_init_buffer
#define yy_flush_buffer base_yy_flush_buffer
#define yy_load_buffer_state base_yy_load_buffer_state
#define yy_switch_to_buffer base_yy_switch_to_buffer
#define yyin base_yyin
#define yyleng base_yyleng
#define yylex base_yylex
#define yyout base_yyout
#define yyrestart base_yyrestart
#define yytext base_yytext
#define yywrap base_yywrap
/* A lexical scanner generated by flex */
/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 * $FreeBSD: src/usr.bin/lex/flex.skl,v 1.4 1999/10/27 07:56:44 obrien Exp $
 */
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#include <stdio.h>
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#include <stdlib.h>
#include <unistd.h>
/* Use prototypes in function declarations. */
#define YY_USE_PROTOS
/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST
#else  /* ! __cplusplus */
#if __STDC__
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif /* __STDC__ */
#endif /* ! __cplusplus */
#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif
#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
/* Returned upon end-of-file. */
#define YY_NULL 0
/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )
#define YY_END_OF_BUFFER_CHAR 0
/* Size of default input buffer. */
#define YY_BUF_SIZE 16384
typedef struct yy_buffer_state *YY_BUFFER_STATE;
extern int yyleng;
extern FILE *yyin, *yyout;
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *     if ( condition_holds )
 *         yyless( 5 );
 *     else
 *         do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */
/* Return all but the first 'n' matched characters back to the input stream. */
#define yyless(n) \
       do \
             { \
             /* Undo effects of setting up yytext. */ \
             *yy_cp = yy_hold_char; \
             YY_RESTORE_YY_MORE_OFFSET \
             yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
             YY_DO_BEFORE_ACTION; /* set up yytext again */ \
             } \
       while ( 0 )
#define unput(c) yyunput( c, yytext_ptr )
/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;
struct yy_buffer_state {
       FILE *yy_input_file;
       char *yy_ch_buf;           /* input buffer */
       char *yy_buf_pos;         /* current position in input buffer */
       /* Size of input buffer in bytes, not including room for EOB
        * characters.
        */
       yy_size_t yy_buf_size;
       /* Number of characters read into yy_ch_buf, not including EOB
        * characters.
        */
       int yy_n_chars;
       /* Whether we "own" the buffer - i.e., we know we created it,
        * and can realloc() it to grow it, and should free() it to
        * delete it.
        */
       int yy_is_our_buffer;
       /* Whether this is an "interactive" input source; if so, and
        * if we're using stdio for input, then we want to use getc()
        * instead of fread(), to make sure we stop fetching input after
        * each newline.
        */
       int yy_is_interactive;
       /* Whether we're considered to be at the beginning of a line.
        * If so, '^' rules will be active on the next match, otherwise
        * not.
        */
       int yy_at_bol;
       /* Whether to try to fill the input buffer when we reach the
        * end of it.
        */
       int yy_fill_buffer;
       int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
       /* When an EOF's been seen but there's still some text to process
        * then we mark the buffer as YY_EOF_PENDING, to indicate that we
        * shouldn't try reading from the input source any more.  We might
        * still have a bunch of tokens to match, though, because of
        * possible backing-up.
        *
        * When we actually see the EOF, we change the status to "new"
        * (via yyrestart()), so that the user can continue scanning by
        * just pointing yyin at a new input file.
        */
#define YY_BUFFER_EOF_PENDING 2
       };
static YY_BUFFER_STATE yy_current_buffer = 0;
/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;         /* number of characters read into yy_ch_buf */
int yyleng;
/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;               /* whether we need to initialize */
static int yy_start = 0;       /* start state number */
/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )
YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));
static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));
#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
       { \
       if ( ! yy_current_buffer ) \
             yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
       yy_current_buffer->yy_is_interactive = is_interactive; \
       }
#define yy_set_bol(at_bol) \
       { \
       if ( ! yy_current_buffer ) \
             yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
       yy_current_buffer->yy_at_bol = at_bol; \
       }
#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext
static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));
/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
       yytext_ptr = yy_bp; \
       yyleng = (int) (yy_cp - yy_bp); \
       yy_hold_char = *yy_cp; \
       *yy_cp = '\0'; \
       yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
static yyconst short int yy_accept[126] =
    {   0,
        0,    0,   10,   10,    0,    0,    0,    0,    0,    0,
        0,    0,   35,   33,    1,    1,   27,   21,   26,   26,
       15,   26,   26,   26,   26,   29,   26,   32,   32,   32,
       10,    8,    5,    5,    6,    6,   24,   22,    9,   14,
       18,   16,   34,   27,   28,    1,   30,    2,   30,   29,
        0,   25,   32,    7,   13,   10,    0,    0,    0,    5,
        0,    4,    3,   24,   23,    9,    0,    0,    0,   18,
        0,    0,   17,    0,   19,    1,    1,    2,   30,    0,
       31,    0,   12,    0,    0,    3,    0,   11,    0,    0,
        0,   20,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   12,    0,
        0,    0,    0,   11,    0,    0,    0,    0,   20,    0,
        0,    0,    0,    0,    0
    } ;
static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    5,    7,    8,    5,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   10,    8,
        8,    8,    5,    5,   18,   19,   18,   18,   20,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   21,   18,   18,
       10,   22,   10,    8,   18,    5,   18,   19,   18,   18,
       20,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   21,
       18,   18,    1,    5,    1,    5,    1,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18
    } ;
static yyconst int yy_meta[23] =
    {   0,
        1,    2,    3,    3,    4,    5,    4,    4,    6,    1,
        7,    4,    8,    1,    7,    9,    1,    9,    9,    9,
        9,   10
    } ;
static yyconst short int yy_base[151] =
    {   0,
        0,    0,  133,  132,   18,   29,  134,  133,  125,  124,
       23,   26,  132,  579,  579,  579,    0,  579,  115,    0,
      579,  579,  117,  113,  117,   33,  110,    0,  113,  112,
        0,   52,    0,    0,   13,  109,    0,  113,    0,   64,
        0,   76,    0,    0,  102,   85,   23,    0,   30,   43,
       48,  579,    0,  579,  579,    0,    0,   49,  104,    0,
       58,  579,    0,    0,  579,    0,    0,   61,  103,    0,
      106,   62,  579,   97,  579,    0,   96,    0,   56,   90,
       89,   73,  579,   89,  110,    0,   74,  579,   86,  122,
       75,  579,   82,  134,  146,  158,  170,  182,  194,  206,
      218,  230,  242,  254,  266,  278,  290,    0,    0,   81,
      302,  314,    0,    0,   78,  326,  338,    0,    0,   68,
      350,   39,   38,   25,  579,  363,  373,  383,  393,  403,
      410,   18,  418,  428,  438,  448,  458,  467,  477,  484,
      491,  496,  503,  510,  518,  528,  538,  548,  558,  568
    } ;
static yyconst short int yy_def[151] =
    {   0,
      125,    1,  126,  126,  127,  127,  128,  128,  129,  129,
      130,  130,  125,  125,  125,  125,  131,  125,  131,  131,
      125,  125,  131,  125,  131,  125,  125,  132,  132,  132,
      133,  125,  134,  134,  125,  125,  135,  125,  136,  125,
      137,  125,  138,  131,  125,  139,  125,  140,  125,  125,
      125,  125,  132,  125,  125,  133,   32,  141,  125,  134,
      125,  125,  142,  135,  125,  136,   40,  143,  125,  137,
       42,  144,  125,  125,  125,  139,  139,  140,  125,  125,
      125,  141,  125,  125,  145,  142,  143,  125,  125,  146,
      144,  125,  125,  147,  148,  145,  145,  145,  149,  146,
      146,  146,  150,  147,  147,  147,  148,  107,  107,  107,
      145,  149,  112,  112,  112,  146,  150,  117,  117,  117,
      147,  107,  112,  117,    0,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125
    } ;
static yyconst short int yy_nxt[602] =
    {   0,
       14,   15,   16,   15,   17,   18,   19,   20,   21,   22,
       20,   20,   23,   24,   25,   26,   27,   28,   29,   28,
       30,   14,   34,   61,   34,   34,   53,   62,   35,   34,
       34,   42,   36,   34,   42,   34,   34,  124,   47,   35,
       34,   34,   51,   36,   43,   79,   49,   43,   50,   51,
      123,  122,   51,   57,   58,   58,   49,   83,   50,   80,
       80,   84,   51,   81,   59,   67,   68,   68,   61,   88,
       92,   79,   62,   89,   93,   51,   69,   71,   72,   72,
      124,   83,   88,   92,   73,   84,   89,   93,   74,   77,
      123,   77,   77,  122,  103,   77,   77,   77,   99,   77,
       77,   95,   77,   77,   81,   81,   77,   77,   77,   94,
       77,   97,   58,   58,  125,   90,   85,   45,   65,   63,
       55,   54,   98,  101,   68,   68,   52,   48,   47,   46,
       45,  125,   40,   40,  102,  105,   72,   72,   38,   38,
       32,   32,  125,  125,  125,  125,  106,  108,   82,   82,
      125,  125,  125,  125,  109,  125,  125,  125,  110,   97,
       58,   58,  125,  125,  125,  125,  125,  125,  125,  125,
       98,   97,   58,   58,  125,  125,  125,  125,  125,  125,
      125,  125,   98,   97,   58,   58,  125,  125,  125,  125,
      125,  125,  125,  125,  111,  113,   87,   87,  125,  125,
      125,  125,  114,  125,  125,  125,  115,  101,   68,   68,
      125,  125,  125,  125,  125,  125,  125,  125,  102,  101,
       68,   68,  125,  125,  125,  125,  125,  125,  125,  125,
      102,  101,   68,   68,  125,  125,  125,  125,  125,  125,
      125,  125,  116,  118,   91,   91,  125,  125,  125,  125,
      119,  125,  125,  125,  120,  105,   72,   72,  125,  125,
      125,  125,  125,  125,  125,  125,  106,  105,   72,   72,
      125,  125,  125,  125,  125,  125,  125,  125,  106,  105,
       72,   72,  125,  125,  125,  125,  125,  125,  125,  125,
      121,  108,   82,   82,  125,  125,  125,  125,  109,  125,
      125,  125,  110,   97,   58,   58,  125,  125,  125,  125,
      125,  125,  125,  125,  111,  113,   87,   87,  125,  125,
      125,  125,  114,  125,  125,  125,  115,  101,   68,   68,
      125,  125,  125,  125,  125,  125,  125,  125,  116,  118,
       91,   91,  125,  125,  125,  125,  119,  125,  125,  125,
      120,  105,   72,   72,  125,  125,  125,  125,  125,  125,
      125,  125,  121,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   44,  125,  125,   44,   44,   56,   56,
       56,   56,   56,  125,   56,   56,   56,   56,   60,   60,
       60,   60,   60,   60,  125,   60,   60,   60,   64,   64,
       64,   64,  125,   64,   64,   64,   64,   64,   66,   66,
       66,   66,   66,  125,   66,   66,   66,   66,   70,   70,
       70,   70,   70,  125,   70,   70,   70,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   76,   76,  125,
       76,   76,   76,   76,   76,   76,   76,   78,  125,  125,
       78,   78,   82,   82,  125,  125,   82,  125,   82,   86,
      125,  125,   86,   86,   87,   87,  125,  125,   87,  125,
       87,   91,   91,  125,  125,   91,  125,   91,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,   13,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125
    } ;
static yyconst short int yy_chk[602] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,   35,    5,    5,  132,   35,    5,    5,
        5,   11,    5,    6,   12,    6,    6,  124,   47,    6,
        6,    6,   47,    6,   11,   49,   26,   12,   26,   49,
      123,  122,   26,   32,   32,   32,   50,   58,   50,   51,
       51,   58,   50,   51,   32,   40,   40,   40,   61,   68,
       72,   79,   61,   68,   72,   79,   40,   42,   42,   42,
      120,   82,   87,   91,   42,   82,   87,   91,   42,   46,
      115,   46,   46,  110,   93,   46,   46,   46,   89,   46,
       77,   84,   77,   77,   81,   80,   77,   77,   77,   74,
       77,   85,   85,   85,   71,   69,   59,   45,   38,   36,
       30,   29,   85,   90,   90,   90,   27,   25,   24,   23,
       19,   13,   10,    9,   90,   94,   94,   94,    8,    7,
        4,    3,    0,    0,    0,    0,   94,   95,   95,   95,
        0,    0,    0,    0,   95,    0,    0,    0,   95,   96,
       96,   96,    0,    0,    0,    0,    0,    0,    0,    0,
       96,   97,   97,   97,    0,    0,    0,    0,    0,    0,
        0,    0,   97,   98,   98,   98,    0,    0,    0,    0,
        0,    0,    0,    0,   98,   99,   99,   99,    0,    0,
        0,    0,   99,    0,    0,    0,   99,  100,  100,  100,
        0,    0,    0,    0,    0,    0,    0,    0,  100,  101,
      101,  101,    0,    0,    0,    0,    0,    0,    0,    0,
      101,  102,  102,  102,    0,    0,    0,    0,    0,    0,
        0,    0,  102,  103,  103,  103,    0,    0,    0,    0,
      103,    0,    0,    0,  103,  104,  104,  104,    0,    0,
        0,    0,    0,    0,    0,    0,  104,  105,  105,  105,
        0,    0,    0,    0,    0,    0,    0,    0,  105,  106,
      106,  106,    0,    0,    0,    0,    0,    0,    0,    0,
      106,  107,  107,  107,    0,    0,    0,    0,  107,    0,
        0,    0,  107,  111,  111,  111,    0,    0,    0,    0,
        0,    0,    0,    0,  111,  112,  112,  112,    0,    0,
        0,    0,  112,    0,    0,    0,  112,  116,  116,  116,
        0,    0,    0,    0,    0,    0,    0,    0,  116,  117,
      117,  117,    0,    0,    0,    0,  117,    0,    0,    0,
      117,  121,  121,  121,    0,    0,    0,    0,    0,    0,
        0,    0,  121,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  131,    0,    0,  131,  131,  133,  133,
      133,  133,  133,    0,  133,  133,  133,  133,  134,  134,
      134,  134,  134,  134,    0,  134,  134,  134,  135,  135,
      135,  135,    0,  135,  135,  135,  135,  135,  136,  136,
      136,  136,  136,    0,  136,  136,  136,  136,  137,  137,
      137,  137,  137,    0,  137,  137,  137,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  139,  139,    0,
      139,  139,  139,  139,  139,  139,  139,  140,    0,    0,
      140,  140,  141,  141,    0,    0,  141,    0,  141,  142,
        0,    0,  142,  142,  143,  143,    0,    0,  143,    0,
      143,  144,  144,    0,    0,  144,    0,  144,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125
    } ;
static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;
/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#define INITIAL 0
/*-------------------------------------------------------------------------
 *
 * scan.l
 *       lexical scanner for PostgreSQL
 *
 * Portions Copyright (c) 1996-2001, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 *
 * IDENTIFICATION
 *       $Header: /cvsroot/pgsql/src/backend/parser/scan.l,v 1.90 2001/09/07 23:17:14 tgl Exp $
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"
#include <ctype.h>
#include <unistd.h>
#ifndef __linux__
#include <math.h>
#endif
#include <errno.h>
#include "miscadmin.h"
#include "nodes/parsenodes.h"
#include "nodes/pg_list.h"
#include "parser/gramparse.h"
#include "parser/keywords.h"
#include "parser/parse.h"
#include "parser/scansup.h"
#include "utils/builtins.h"
#ifdef MULTIBYTE
#include "mb/pg_wchar.h"
#endif
extern char *parseString;
static char *parseCh;
/* some versions of lex define this as a macro */
#if defined(yywrap)
#undef yywrap
#endif /* yywrap */
/* set up my input handler --- need one flavor for flex, one for lex */
#if defined(FLEX_SCANNER)
#define YY_NEVER_INTERACTIVE 1
#define YY_NO_UNPUT
static int myinput(char* buf, int max);
#undef YY_INPUT
#define YY_INPUT(buf,result,max) {result = myinput(buf,max);}
/* No reason to constrain amount of data slurped per myinput() call. */
#define YY_READ_BUF_SIZE 16777216
/* Avoid exit() on fatal scanner errors (a bit ugly -- see yy_fatal_error) */
#define fprintf(file, fmt, msg)  elog(FATAL, "%s", (msg))
#else /* !FLEX_SCANNER */
#undef input
int input();
#undef unput
void unput(char);
#endif /* FLEX_SCANNER */
extern YYSTYPE yylval;
static int         xcdepth = 0;       /* depth of nesting in slash-star comments */
/*
 * literalbuf is used to accumulate literal values when multiple rules
 * are needed to parse a single literal.  Call startlit to reset buffer
 * to empty, addlit to add text.  Note that the buffer is palloc'd and
 * starts life afresh on every parse cycle.
 */
static char       *literalbuf;       /* expandable buffer */
static int         literallen;               /* actual current length */
static int         literalalloc;      /* current allocated buffer size */
#define startlit()  (literalbuf[0] = '\0', literallen = 0)
static void addlit(char *ytext, int yleng);
/*
 * OK, here is a short description of lex/flex rules behavior.
 * The longest pattern which matches an input string is always chosen.
 * For equal-length patterns, the first occurring in the rules list is chosen.
 * INITIAL is the starting state, to which all non-conditional rules apply.
 * Exclusive states change parsing rules while the state is active.  When in
 * an exclusive state, only those rules defined for that state apply.
 *
 * We use exclusive states for quoted strings, extended comments,
 * and to eliminate parsing troubles for numeric strings.
 * Exclusive states:
 *  <xbit> bit string literal
 *  <xc> extended C-style comments - thomas 1997-07-12
 *  <xd> delimited identifiers (double-quoted identifiers) - thomas 1997-10-27
 *  <xh> hexadecimal numeric string - thomas 1997-11-16
 *  <xq> quoted strings - thomas 1997-07-30
 */
#define xbit 1
#define xc 2
#define xd 3
#define xh 4
#define xq 5
/* Bit string
 */
/* Hexadecimal number
 */
/* Extended quote
 * xqdouble implements SQL92 embedded quote
 * xqcat allows strings to cross input lines
 * Note: reduction of '' and \ sequences to output text is done in scanstr(),
 * not by rules here.  But we do get rid of xqcat sequences here.
 */
/* Delimited quote
 * Allows embedded spaces and other special characters into identifiers.
 */
/* C-style comments
 *
 * The "extended comment" syntax closely resembles allowable operator syntax.
 * The tricky part here is to get lex to recognize a string starting with
 * slash-star as a comment, when interpreting it as an operator would produce
 * a longer match --- remember lex will prefer a longer match!  Also, if we
 * have something like plus-slash-star, lex will think this is a 3-character
 * operator whereas we want to see it as a + operator and a comment start.
 * The solution is two-fold:
 * 1. append {op_chars}* to xcstart so that it matches as much text as
 *    {operator} would. Then the tie-breaker (first matching rule of same
 *    length) ensures xcstart wins.  We put back the extra stuff with yyless()
 *    in case it contains a star-slash that should terminate the comment.
 * 2. In the operator rule, check for slash-star within the operator, and
 *    if found throw it back with yyless().  This handles the plus-slash-star
 *    problem.
 * SQL92-style comments, which start with dash-dash, have similar interactions
 * with the operator rule.
 */
/*
 * "self" is the set of chars that should be returned as single-character
 * tokens.  "op_chars" is the set of chars that can make up "Op" tokens,
 * which can be one or more characters long (but if a single-char token
 * appears in the "self" set, it is not to be returned as an Op).  Note
 * that the sets overlap, but each has some chars that are not in the other.
 *
 * If you change either set, adjust the character lists appearing in the
 * rule for "operator"!
 */
/* we no longer allow unary minus in numbers. 
 * instead we pass it separately to parser. there it gets
 * coerced via doNegate() -- Leon aug 20 1999 
 */
/*
 * In order to make the world safe for Windows and Mac clients as well as
 * Unix ones, we accept either \n or \r as a newline.  A DOS-style \r\n
 * sequence will be seen as two successive newlines, but that doesn't cause
 * any problems.  SQL92-style comments, which start with -- and extend to the
 * next newline, are treated as equivalent to a single whitespace character.
 *
 * NOTE a fine point: if there is no newline following --, we will absorb
 * everything to the end of the input as a comment.  This is correct.  Older
 * versions of Postgres failed to recognize -- as a comment if the input
 * did not end with a newline.
 *
 * XXX perhaps \f (formfeed) should be treated as a newline as well?
 */
/*
 * SQL92 requires at least one newline in the whitespace separating
 * string literals that are to be concatenated.  Silly, but who are we
 * to argue?  Note that {whitespace_with_newline} should not have * after
 * it, whereas {whitespace} should generally have a * after it...
 */
/* DO NOT PUT ANY COMMENTS IN THE FOLLOWING SECTION.
 * AT&T lex does not properly handle C-style comments in this second lex block.
 * So, put comments here. thomas - 1997-09-08
 *
 * Quoted strings must allow some special characters such as single-quote
 *  and newline.
 * Embedded single-quotes are implemented both in the SQL92-standard
 *  style of two adjacent single quotes "''" and in the Postgres/Java style
 *  of escaped-quote "\'".
 * Other embedded escaped characters are matched explicitly and the leading
 *  backslash is dropped from the string. - thomas 1997-09-24
 * Note that xcstart must appear before operator, as explained above!
 *  Also whitespace (comment) must appear before operator.
 */
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */
#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif
#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif
#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif
#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif
#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif
#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif
#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif
#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif
/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
       if ( yy_current_buffer->yy_is_interactive ) \
             { \
             int c = '*', n; \
             for ( n = 0; n < max_size && \
                       (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
                  buf[n] = (char) c; \
             if ( c == '\n' ) \
                  buf[n++] = (char) c; \
             if ( c == EOF && ferror( yyin ) ) \
                  YY_FATAL_ERROR( "input in flex scanner failed" ); \
             result = n; \
             } \
       else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
               && ferror( yyin ) ) \
             YY_FATAL_ERROR( "input in flex scanner failed" );
#endif
/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif
/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif
/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif
/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif
/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif
/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif
#define YY_RULE_SETUP \
       YY_USER_ACTION
YY_DECL {
       register yy_state_type yy_current_state;
       register char *yy_cp, *yy_bp;
       register int yy_act;
       if ( yy_init ) {
             yy_init = 0;
#ifdef YY_USER_INIT
             YY_USER_INIT;
#endif
             if ( ! yy_start )
                  yy_start = 1;       /* first start state */
             if ( ! yyin )
                  yyin = stdin;
             if ( ! yyout )
                  yyout = stdout;
             if ( ! yy_current_buffer )
                  yy_current_buffer =
                      yy_create_buffer( yyin, YY_BUF_SIZE );
             yy_load_buffer_state(); }
       while ( 1 )     /* loops until end-of-file is reached */ {
             yy_cp = yy_c_buf_p;
             /* Support of yytext. */
             *yy_cp = yy_hold_char;
             /* yy_bp points to the position in yy_ch_buf of the start of
              * the current run.
              */
             yy_bp = yy_cp;
             yy_current_state = yy_start;
yy_match:
             do {
                  register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
                  if ( yy_accept[yy_current_state] ) {
                      yy_last_accepting_state = yy_current_state;
                      yy_last_accepting_cpos = yy_cp; }
                  while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
                      yy_current_state = (int) yy_def[yy_current_state];
                      if ( yy_current_state >= 126 )
                         yy_c = yy_meta[(unsigned int) yy_c]; }
                  yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
                  ++yy_cp; }
             while ( yy_base[yy_current_state] != 579 );
yy_find_action:
             yy_act = yy_accept[yy_current_state];
             if ( yy_act == 0 )
                  { /* have to back up */
                  yy_cp = yy_last_accepting_cpos;
                  yy_current_state = yy_last_accepting_state;
                  yy_act = yy_accept[yy_current_state]; }
             YY_DO_BEFORE_ACTION;
do_action:     /* This label is used only to access EOF actions. */
             switch ( yy_act )
       { /* beginning of action switch */
                  case 0: /* must back up */
                  /* undo the effects of YY_DO_BEFORE_ACTION */
                  *yy_cp = yy_hold_char;
                  yy_cp = yy_last_accepting_cpos;
                  yy_current_state = yy_last_accepting_state;
                  goto yy_find_action;
case 1:
YY_RULE_SETUP
{ /* ignore */ }
       YY_BREAK
case 2:
YY_RULE_SETUP {
                         xcdepth = 0;
                         BEGIN(xc);
                         /* Put back any characters past slash-star; see above */
                         yyless(2); }
       YY_BREAK
case 3:
YY_RULE_SETUP {
                         xcdepth++;
                         /* Put back any characters past slash-star; see above */
                         yyless(2); }
       YY_BREAK
case 4:
YY_RULE_SETUP {
                         if (xcdepth <= 0)
                           BEGIN(INITIAL);
                         else
                           xcdepth--; }
       YY_BREAK
case 5:
YY_RULE_SETUP
{ /* ignore */ }
       YY_BREAK
case 6:
YY_RULE_SETUP
{ /* ignore */ }
       YY_BREAK
case YY_STATE_EOF(xc):
{ elog(ERROR, "Unterminated /* comment"); }
       YY_BREAK
case 7:
YY_RULE_SETUP {
                         BEGIN(xbit);
                         startlit();
                         addlit("b", 1); }
       YY_BREAK
case 8:
YY_RULE_SETUP {
                         BEGIN(INITIAL);
                         if (literalbuf[strspn(literalbuf + 1, "01") + 1] != '\0')
                           elog(ERROR, "invalid bit string input: '%s'",
                             literalbuf);
                         yylval.str = pstrdup(literalbuf);
                         return BITCONST; }
       YY_BREAK
case 9:
case 10:
YY_RULE_SETUP {
                         addlit(yytext, yyleng); }
       YY_BREAK
case 11:
case 12:
YY_RULE_SETUP {
                         /* ignore */ }
       YY_BREAK
case YY_STATE_EOF(xbit):
{ elog(ERROR, "unterminated bit string literal"); }
       YY_BREAK
case 13:
YY_RULE_SETUP {
                         BEGIN(xh);
                         startlit(); }
       YY_BREAK
case 14:
YY_RULE_SETUP {
                         long val;
                         char* endptr;
                         BEGIN(INITIAL);
                         errno = 0;
                         val = strtol(literalbuf, &endptr, 16);
                         if (*endptr != '\0' || errno == ERANGE
#ifdef HAVE_LONG_INT_64
                           /* if long > 32 bits, check for overflow of int4 */
                           || val != (long) ((int32) val)
#endif
                           )
                           elog(ERROR, "Bad hexadecimal integer input '%s'",
                             literalbuf);
                         yylval.ival = val;
                         return ICONST; }
       YY_BREAK
case YY_STATE_EOF(xh):
{ elog(ERROR, "Unterminated hexadecimal integer"); }
       YY_BREAK
case 15:
YY_RULE_SETUP {
                         BEGIN(xq);
                         startlit(); }
       YY_BREAK
case 16:
YY_RULE_SETUP {
                         BEGIN(INITIAL);
                         yylval.str = scanstr(literalbuf);
                         return SCONST; }
       YY_BREAK
case 17:
case 18:
case 19:
YY_RULE_SETUP {
                         addlit(yytext, yyleng); }
       YY_BREAK
case 20:
YY_RULE_SETUP {
                         /* ignore */ }
       YY_BREAK
case YY_STATE_EOF(xq):
{ elog(ERROR, "Unterminated quoted string"); }
       YY_BREAK
case 21:
YY_RULE_SETUP {
                         BEGIN(xd);
                         startlit(); }
       YY_BREAK
case 22:
YY_RULE_SETUP {
                         BEGIN(INITIAL);
                         if (strlen(literalbuf) == 0)
                           elog(ERROR, "zero-length delimited identifier");
                         if (strlen(literalbuf) >= NAMEDATALEN) {
#ifdef MULTIBYTE
                           int len;
                           len = pg_mbcliplen(literalbuf,strlen(literalbuf),NAMEDATALEN-1);
                           elog(NOTICE, "identifier \"%s\" will be truncated to \"%.*s\"",
                             literalbuf, len, literalbuf);
                           literalbuf[len] = '\0';
#else
                           elog(NOTICE, "identifier \"%s\" will be truncated to \"%.*s\"",
                             literalbuf, NAMEDATALEN-1, literalbuf);
                           literalbuf[NAMEDATALEN-1] = '\0';
#endif
                         }
                         yylval.str = pstrdup(literalbuf);
                         return IDENT; }
       YY_BREAK
case 23:
YY_RULE_SETUP {
                         addlit(yytext, yyleng-1); }
       YY_BREAK
case 24:
YY_RULE_SETUP {
                         addlit(yytext, yyleng); }
       YY_BREAK
case YY_STATE_EOF(xd):
{ elog(ERROR, "Unterminated quoted identifier"); }
       YY_BREAK
case 25:
YY_RULE_SETUP
{ return TYPECAST; }
       YY_BREAK
case 26:
YY_RULE_SETUP
{ return yytext[0]; }
       YY_BREAK
case 27:
YY_RULE_SETUP {
                         /*
                          * Check for embedded slash-star or dash-dash; those
                          * are comment starts, so operator must stop there.
                          * Note that slash-star or dash-dash at the first
                          * character will match a prior rule, not this one.
                          */
                         int             nchars = yyleng;
                         char   *slashstar = strstr((char*)yytext, "/*");
                         char   *dashdash = strstr((char*)yytext, "--");
                         if (slashstar && dashdash) {
                           /* if both appear, take the first one */
                           if (slashstar > dashdash)
                            slashstar = dashdash; }
                         else if (!slashstar)
                           slashstar = dashdash;
                         if (slashstar)
                           nchars = slashstar - ((char*)yytext);
                         /*
                          * For SQL92 compatibility, '+' and '-' cannot be the
                          * last char of a multi-char operator unless the operator
                          * contains chars that are not in SQL92 operators.
                          * The idea is to lex '=-' as two operators, but not
                          * to forbid operator names like '?-' that could not be
                          * sequences of SQL92 operators.
                          */
                         while (nchars > 1 &&
                              (yytext[nchars-1] == '+' ||
                            yytext[nchars-1] == '-')) {
                           int           ic;
                           for (ic = nchars-2; ic >= 0; ic--) {
                            if (strchr("~!@#^&|`?$%", yytext[ic]))
                                    break; }
                           if (ic >= 0)
                            break; /* found a char that makes it OK */
                           nchars--; /* else remove the +/-, and check again */ }
                         if (nchars < yyleng) {
                           /* Strip the unwanted chars from the token */
                           yyless(nchars);
                           /*
                            * If what we have left is only one char, and it's
                            * one of the characters matching "self", then
                            * return it as a character token the same way
                            * that the "self" rule would have.
                            */
                           if (nchars == 1 &&
                            strchr(",()[].;$:+-*/%^<>=", yytext[0]))
                            return yytext[0]; }
                         /* Convert "!=" operator to "<>" for compatibility */
                         if (strcmp((char*)yytext, "!=") == 0)
                           yylval.str = pstrdup("<>");
                         else
                           yylval.str = pstrdup((char*)yytext);
                         return Op; }
       YY_BREAK
case 28:
YY_RULE_SETUP {
                         yylval.ival = atol((char*)&yytext[1]);
                         return PARAM; }
       YY_BREAK
case 29:
YY_RULE_SETUP {
                         long val;
                         char* endptr;
                         errno = 0;
                         val = strtol((char *)yytext, &endptr, 10);
                         if (*endptr != '\0' || errno == ERANGE
#ifdef HAVE_LONG_INT_64
                           /* if long > 32 bits, check for overflow of int4 */
                           || val != (long) ((int32) val)
#endif
                           ) {
                           /* integer too large, treat it as a float */
                           yylval.str = pstrdup((char*)yytext);
                           return FCONST; }
                         yylval.ival = val;
                         return ICONST; }
       YY_BREAK
case 30:
YY_RULE_SETUP {
                         yylval.str = pstrdup((char*)yytext);
                         return FCONST; }
       YY_BREAK
case 31:
YY_RULE_SETUP {
                         yylval.str = pstrdup((char*)yytext);
                         return FCONST; }
       YY_BREAK
case 32:
YY_RULE_SETUP {
                         ScanKeyword          *keyword;
                         int                      i;
                         /* Is it a keyword? */
                         keyword = ScanKeywordLookup((char*) yytext);
                         if (keyword != NULL)
                           return keyword->value;
                         /*
                          * No.  Convert the identifier to lower case, and truncate
                          * if necessary.
                          *
                          * Note: here we use a locale-dependent case conversion,
                          * which seems appropriate under SQL99 rules, whereas
                          * the keyword comparison was NOT locale-dependent.
                          */
                         for (i = 0; yytext[i]; i++) {
                           if (isupper((unsigned char) yytext[i]))
                            yytext[i] = tolower((unsigned char) yytext[i]); }
                         if (i >= NAMEDATALEN) {
#ifdef MULTIBYTE
                           int len;
                           len = pg_mbcliplen(yytext,i,NAMEDATALEN-1);
                        elog(NOTICE, "identifier \"%s\" will be truncated to \"%.*s\"",
                             yytext, len, yytext);
                           yytext[len] = '\0';
#else
                        elog(NOTICE, "identifier \"%s\" will be truncated to \"%.*s\"",
                             yytext, NAMEDATALEN-1, yytext);
                           yytext[NAMEDATALEN-1] = '\0';
#endif
                    }
                         yylval.str = pstrdup((char*) yytext);
                         return IDENT; }
       YY_BREAK
case 33:
YY_RULE_SETUP
{ return yytext[0]; }
       YY_BREAK
case 34:
YY_RULE_SETUP
ECHO;
       YY_BREAK
case YY_STATE_EOF(INITIAL):
       yyterminate();
       case YY_END_OF_BUFFER: {
             /* Amount of text matched not including the EOB char. */
             int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;
             /* Undo the effects of YY_DO_BEFORE_ACTION. */
             *yy_cp = yy_hold_char;
             YY_RESTORE_YY_MORE_OFFSET
             if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW ) {
                  /* We're scanning a new file or input source.  It's
                   * possible that this happened because the user
                   * just pointed yyin at a new source and called
                   * yylex().  If so, then we have to assure
                   * consistency between yy_current_buffer and our
                   * globals.  Here is the right place to do so, because
                   * this is the first action (other than possibly a
                   * back-up) that will match for the new input source.
                   */
                  yy_n_chars = yy_current_buffer->yy_n_chars;
                  yy_current_buffer->yy_input_file = yyin;
                  yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL; }
             /* Note that here we test for yy_c_buf_p "<=" to the position
              * of the first EOB in the buffer, since yy_c_buf_p will
              * already have been incremented past the NUL character
              * (since all states make transitions on EOB to the
              * end-of-buffer state).  Contrast this with the test
              * in input().
              */
             if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
                  { /* This was really a NUL. */
                  yy_state_type yy_next_state;
                  yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;
                  yy_current_state = yy_get_previous_state();
                  /* Okay, we're now positioned to make the NUL
                   * transition.  We couldn't have
                   * yy_get_previous_state() go ahead and do it
                   * for us because it doesn't know how to deal
                   * with the possibility of jamming (and we don't
                   * want to build jamming into it because then it
                   * will run more slowly).
                   */
                  yy_next_state = yy_try_NUL_trans( yy_current_state );
                  yy_bp = yytext_ptr + YY_MORE_ADJ;
                  if ( yy_next_state ) {
                      /* Consume the NUL. */
                      yy_cp = ++yy_c_buf_p;
                      yy_current_state = yy_next_state;
                      goto yy_match; }
                  else {
                      yy_cp = yy_c_buf_p;
                      goto yy_find_action; } }
             else switch ( yy_get_next_buffer() ) {
                  case EOB_ACT_END_OF_FILE: {
                      yy_did_buffer_switch_on_eof = 0;
                      if ( yywrap() ) {
                         /* Note: because we've taken care in
                          * yy_get_next_buffer() to have set up
                          * yytext, we can now set up
                          * yy_c_buf_p so that if some total
                          * hoser (like flex itself) wants to
                          * call the scanner after we return the
                          * YY_NULL, it'll still work - another
                          * YY_NULL will get returned.
                          */
                         yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                         yy_act = YY_STATE_EOF(YY_START);
                         goto do_action; }
                      else {
                         if ( ! yy_did_buffer_switch_on_eof )
                           YY_NEW_FILE; }
                      break; }
                  case EOB_ACT_CONTINUE_SCAN:
                      yy_c_buf_p =
                         yytext_ptr + yy_amount_of_matched_text;
                      yy_current_state = yy_get_previous_state();
                      yy_cp = yy_c_buf_p;
                      yy_bp = yytext_ptr + YY_MORE_ADJ;
                      goto yy_match;
                  case EOB_ACT_LAST_MATCH:
                      yy_c_buf_p =
                      &yy_current_buffer->yy_ch_buf[yy_n_chars];
                      yy_current_state = yy_get_previous_state();
                      yy_cp = yy_c_buf_p;
                      yy_bp = yytext_ptr + YY_MORE_ADJ;
                      goto yy_find_action; }
             break; }
       default:
             YY_FATAL_ERROR(
                  "fatal flex scanner internal error--no action found" );
       } /* end of action switch */
             } /* end of scanning one token */
       } /* end of yylex */
/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *     EOB_ACT_LAST_MATCH -
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer() {
       register char *dest = yy_current_buffer->yy_ch_buf;
       register char *source = yytext_ptr;
       register int number_to_move, i;
       int ret_val;
       if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
             YY_FATAL_ERROR(
             "fatal flex scanner internal error--end of buffer missed" );
       if ( yy_current_buffer->yy_fill_buffer == 0 )
             { /* Don't try to fill the buffer, so this is an EOF. */
             if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 ) {
                  /* We matched a single character, the EOB, so
                   * treat this as a final EOF.
                   */
                  return EOB_ACT_END_OF_FILE; }
             else {
                  /* We matched some text prior to the EOB, first
                   * process it.
                   */
                  return EOB_ACT_LAST_MATCH; } }
       /* Try to read more data. */
       /* First move last chars to start of buffer. */
       number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;
       for ( i = 0; i < number_to_move; ++i )
             *(dest++) = *(source++);
       if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
             /* don't do the read, it's not guaranteed to return an EOF,
              * just force an EOF
              */
             yy_current_buffer->yy_n_chars = yy_n_chars = 0;
       else {
             int num_to_read =
                  yy_current_buffer->yy_buf_size - number_to_move - 1;
             while ( num_to_read <= 0 )
                  { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
                  YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else
                  /* just a shorter name for the current buffer */
                  YY_BUFFER_STATE b = yy_current_buffer;
                  int yy_c_buf_p_offset =
                      (int) (yy_c_buf_p - b->yy_ch_buf);
                  if ( b->yy_is_our_buffer ) {
                      int new_size = b->yy_buf_size * 2;
                      if ( new_size <= 0 )
                         b->yy_buf_size += b->yy_buf_size / 8;
                      else
                         b->yy_buf_size *= 2;
                      b->yy_ch_buf = (char *)
                         /* Include room in for 2 EOB chars. */
                         yy_flex_realloc( (void *) b->yy_ch_buf,
                             b->yy_buf_size + 2 ); }
                  else
                      /* Can't grow it, we don't own it. */
                      b->yy_ch_buf = 0;
                  if ( ! b->yy_ch_buf )
                      YY_FATAL_ERROR(
                      "fatal error - scanner input buffer overflow" );
                  yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
                  num_to_read = yy_current_buffer->yy_buf_size -
                           number_to_move - 1;
#endif
                  }
             if ( num_to_read > YY_READ_BUF_SIZE )
                  num_to_read = YY_READ_BUF_SIZE;
             /* Read in more data. */
             YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
                  yy_n_chars, num_to_read );
             yy_current_buffer->yy_n_chars = yy_n_chars; }
       if ( yy_n_chars == 0 ) {
             if ( number_to_move == YY_MORE_ADJ ) {
                  ret_val = EOB_ACT_END_OF_FILE;
                  yyrestart( yyin ); }
             else {
                  ret_val = EOB_ACT_LAST_MATCH;
                  yy_current_buffer->yy_buffer_status =
                      YY_BUFFER_EOF_PENDING; } }
       else
             ret_val = EOB_ACT_CONTINUE_SCAN;
       yy_n_chars += number_to_move;
       yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
       yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
       yytext_ptr = &yy_current_buffer->yy_ch_buf[0];
       return ret_val; }
/* yy_get_previous_state - get the state just before the EOB char was reached */
static yy_state_type yy_get_previous_state() {
       register yy_state_type yy_current_state;
       register char *yy_cp;
       yy_current_state = yy_start;
       for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp ) {
             register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
             if ( yy_accept[yy_current_state] ) {
                  yy_last_accepting_state = yy_current_state;
                  yy_last_accepting_cpos = yy_cp; }
             while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
                  yy_current_state = (int) yy_def[yy_current_state];
                  if ( yy_current_state >= 126 )
                      yy_c = yy_meta[(unsigned int) yy_c]; }
             yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c]; }
       return yy_current_state; }
/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */
#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
       {
       register int yy_is_jam;
       register char *yy_cp = yy_c_buf_p;
       register YY_CHAR yy_c = 1;
       if ( yy_accept[yy_current_state] ) {
             yy_last_accepting_state = yy_current_state;
             yy_last_accepting_cpos = yy_cp; }
       while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
             yy_current_state = (int) yy_def[yy_current_state];
             if ( yy_current_state >= 126 )
                  yy_c = yy_meta[(unsigned int) yy_c]; }
       yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
       yy_is_jam = (yy_current_state == 125);
       return yy_is_jam ? 0 : yy_current_state; }
#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
       {
       register char *yy_cp = yy_c_buf_p;
       /* undo effects of setting up yytext */
       *yy_cp = yy_hold_char;
       if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
             { /* need to shift things up to make room */
             /* +2 for EOB chars. */
             register int number_to_move = yy_n_chars + 2;
             register char *dest = &yy_current_buffer->yy_ch_buf[
                         yy_current_buffer->yy_buf_size + 2];
             register char *source =
                      &yy_current_buffer->yy_ch_buf[number_to_move];
             while ( source > yy_current_buffer->yy_ch_buf )
                  *--dest = *--source;
             yy_cp += (int) (dest - source);
             yy_bp += (int) (dest - source);
             yy_current_buffer->yy_n_chars =
                  yy_n_chars = yy_current_buffer->yy_buf_size;
             if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
                  YY_FATAL_ERROR( "flex scanner push-back overflow" ); }
       *--yy_cp = (char) c;
       yytext_ptr = yy_bp;
       yy_hold_char = *yy_cp;
       yy_c_buf_p = yy_cp; }
#endif /* ifndef YY_NO_UNPUT */
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
       {
       int c;
       *yy_c_buf_p = yy_hold_char;
       if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR ) {
             /* yy_c_buf_p now points to the character we want to return.
              * If this occurs *before* the EOB characters, then it's a
              * valid NUL; if not, then we've hit the end of the buffer.
              */
             if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
                  /* This was really a NUL. */
                  *yy_c_buf_p = '\0';
             else
                  { /* need more input */
                  int offset = yy_c_buf_p - yytext_ptr;
                  ++yy_c_buf_p;
                  switch ( yy_get_next_buffer() ) {
                      case EOB_ACT_LAST_MATCH:
                         /* This happens because yy_g_n_b()
                          * sees that we've accumulated a
                          * token and flags that we need to
                          * try matching the token before
                          * proceeding.  But for input(),
                          * there's no matching to consider.
                          * So convert the EOB_ACT_LAST_MATCH
                          * to EOB_ACT_END_OF_FILE.
                          */
                         /* Reset buffer status. */
                         yyrestart( yyin );
                         /* fall through */
                      case EOB_ACT_END_OF_FILE: {
                         if ( yywrap() )
                           return EOF;
                         if ( ! yy_did_buffer_switch_on_eof )
                           YY_NEW_FILE;
#ifdef __cplusplus
                         return yyinput();
#else
                         return input();
#endif
                         }
                      case EOB_ACT_CONTINUE_SCAN:
                         yy_c_buf_p = yytext_ptr + offset;
                         break; } } }
       c = *(unsigned char *) yy_c_buf_p;    /* cast for 8-bit char's */
       *yy_c_buf_p = '\0';   /* preserve yytext */
       yy_hold_char = *++yy_c_buf_p;
       return c; }
#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
       {
       if ( ! yy_current_buffer )
             yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );
       yy_init_buffer( yy_current_buffer, input_file );
       yy_load_buffer_state(); }
#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
       {
       if ( yy_current_buffer == new_buffer )
             return;
       if ( yy_current_buffer ) {
             /* Flush out information for old buffer. */
             *yy_c_buf_p = yy_hold_char;
             yy_current_buffer->yy_buf_pos = yy_c_buf_p;
             yy_current_buffer->yy_n_chars = yy_n_chars; }
       yy_current_buffer = new_buffer;
       yy_load_buffer_state();
       /* We don't actually know whether we did this switch during
        * EOF (yywrap()) processing, but the only time this flag
        * is looked at is after yywrap() is called, so it's safe
        * to go ahead and always set it.
        */
       yy_did_buffer_switch_on_eof = 1; }
#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
       {
       yy_n_chars = yy_current_buffer->yy_n_chars;
       yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
       yyin = yy_current_buffer->yy_input_file;
       yy_hold_char = *yy_c_buf_p; }
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
       {
       YY_BUFFER_STATE b;
       b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
       if ( ! b )
             YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
       b->yy_buf_size = size;
       /* yy_ch_buf has to be 2 characters longer than the size given because
        * we need to put in 2 end-of-buffer characters.
        */
       b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
       if ( ! b->yy_ch_buf )
             YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
       b->yy_is_our_buffer = 1;
       yy_init_buffer( b, file );
       return b; }
#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
       {
       if ( ! b )
             return;
       if ( b == yy_current_buffer )
             yy_current_buffer = (YY_BUFFER_STATE) 0;
       if ( b->yy_is_our_buffer )
             yy_flex_free( (void *) b->yy_ch_buf );
       yy_flex_free( (void *) b ); }
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
       {
       yy_flush_buffer( b );
       b->yy_input_file = file;
       b->yy_fill_buffer = 1;
#if YY_ALWAYS_INTERACTIVE
       b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
       b->yy_is_interactive = 0;
#else
       b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
       }
#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif
       {
       if ( ! b )
             return;
       b->yy_n_chars = 0;
       /* We always need two end-of-buffer characters.  The first causes
        * a transition to the end-of-buffer state.  The second causes
        * a jam in that state.
        */
       b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
       b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
       b->yy_buf_pos = &b->yy_ch_buf[0];
       b->yy_at_bol = 1;
       b->yy_buffer_status = YY_BUFFER_NEW;
       if ( b == yy_current_buffer )
             yy_load_buffer_state(); }
#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
       {
       YY_BUFFER_STATE b;
       if ( size < 2 ||
            base[size-2] != YY_END_OF_BUFFER_CHAR ||
            base[size-1] != YY_END_OF_BUFFER_CHAR )
             /* They forgot to leave room for the EOB's. */
             return 0;
       b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
       if ( ! b )
             YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );
       b->yy_buf_size = size - 2;    /* "- 2" to take care of EOB's */
       b->yy_buf_pos = b->yy_ch_buf = base;
       b->yy_is_our_buffer = 0;
       b->yy_input_file = 0;
       b->yy_n_chars = b->yy_buf_size;
       b->yy_is_interactive = 0;
       b->yy_at_bol = 1;
       b->yy_fill_buffer = 0;
       b->yy_buffer_status = YY_BUFFER_NEW;
       yy_switch_to_buffer( b );
       return b; }
#endif
#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
       {
       int len;
       for ( len = 0; yy_str[len]; ++len )
             ;
       return yy_scan_bytes( yy_str, len ); }
#endif
#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
       {
       YY_BUFFER_STATE b;
       char *buf;
       yy_size_t n;
       int i;
       /* Get memory for full buffer, including space for trailing EOB's. */
       n = len + 2;
       buf = (char *) yy_flex_alloc( n );
       if ( ! buf )
             YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );
       for ( i = 0; i < len; ++i )
             buf[i] = bytes[i];
       buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;
       b = yy_scan_buffer( buf, n );
       if ( ! b )
             YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );
       /* It's okay to grow etc. this buffer, and we should throw it
        * away when we're done.
        */
       b->yy_is_our_buffer = 1;
       return b; }
#endif
#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
       {
       if ( yy_start_stack_ptr >= yy_start_stack_depth ) {
             yy_size_t new_size;
             yy_start_stack_depth += YY_START_STACK_INCR;
             new_size = yy_start_stack_depth * sizeof( int );
             if ( ! yy_start_stack )
                  yy_start_stack = (int *) yy_flex_alloc( new_size );
             else
                  yy_start_stack = (int *) yy_flex_realloc(
                         (void *) yy_start_stack, new_size );
             if ( ! yy_start_stack )
                  YY_FATAL_ERROR(
                  "out of memory expanding start-condition stack" ); }
       yy_start_stack[yy_start_stack_ptr++] = YY_START;
       BEGIN(new_state); }
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state() {
       if ( --yy_start_stack_ptr < 0 )
             YY_FATAL_ERROR( "start-condition stack underflow" );
       BEGIN(yy_start_stack[yy_start_stack_ptr]); }
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state() {
       return yy_start_stack[yy_start_stack_ptr - 1]; }
#endif
#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif
#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
       {
       (void) fprintf( stderr, "%s\n", msg );
       exit( YY_EXIT_FAILURE ); }
/* Redefine yyless() so it works in section 3 code. */
#undef yyless
#define yyless(n) \
       do \
             { \
             /* Undo effects of setting up yytext. */ \
             yytext[yyleng] = yy_hold_char; \
             yy_c_buf_p = yytext + n; \
             yy_hold_char = *yy_c_buf_p; \
             *yy_c_buf_p = '\0'; \
             yyleng = n; \
             } \
       while ( 0 )
/* Internal utility routines. */
#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
       {
       register int i;
       for ( i = 0; i < n; ++i )
             s1[i] = s2[i]; }
#endif
#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
       {
       register int n;
       for ( n = 0; s[n]; ++n )
             ;
       return n; }
#endif
#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
       {
       return (void *) malloc( size ); }
#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
       {
       /* The cast to (char *) in the following accommodates both
        * implementations that use char* generic pointers, and those
        * that use void* generic pointers.  It works with the latter
        * because both ANSI C and C++ allow castless assignment from
        * any pointer type to void*, and deal with argument conversions
        * as though doing an assignment.
        */
       return (void *) realloc( (char *) ptr, size ); }
#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
       {
       free( ptr ); }
#if YY_MAIN
int main() {
       yylex();
       return 0; }
#endif
void
yyerror(const char *message) {
       elog(ERROR, "parser: %s at or near \"%s\"", message, yytext); }
int
yywrap(void) {
       return(1); }
/*
 scanner_init:
       called by postgres before any actual parsing is done
*/
void
scanner_init(void) {
       /* it's important to set this to NULL
          because input()/myinput() checks the non-nullness of parseCh
          to know when to pass the string to lex/flex */
       parseCh = NULL;
       /* initialize literal buffer to a reasonable but expansible size */
       literalalloc = 128;
       literalbuf = (char *) palloc(literalalloc);
       startlit();
#if defined(FLEX_SCANNER)
       if (YY_CURRENT_BUFFER)
             yy_flush_buffer(YY_CURRENT_BUFFER);
#endif /* FLEX_SCANNER */
       BEGIN INITIAL; }
static void
addlit(char *ytext, int yleng) {
       /* enlarge buffer if needed */
       if ((literallen+yleng) >= literalalloc) {
             do {
                  literalalloc *= 2;
             } while ((literallen+yleng) >= literalalloc);
             literalbuf = (char *) repalloc(literalbuf, literalalloc); }
       /* append new data, add trailing null */
       memcpy(literalbuf+literallen, ytext, yleng);
       literallen += yleng;
       literalbuf[literallen] = '\0'; }
#if !defined(FLEX_SCANNER)
/* get lex input from a string instead of from stdin */
int
input() {
       if (parseCh == NULL)
             parseCh = parseString;
       if (*parseCh == '\0')
             return(0);
       else
             return(*parseCh++); }
/* undo lex input from a string instead of from stdin */
void
unput(char c) {
       if (parseCh == NULL)
             elog(FATAL, "Unput() failed.\n");
       else if (c != 0)
             *--parseCh = c; }
#endif /* !defined(FLEX_SCANNER) */
#ifdef FLEX_SCANNER
/* input routine for flex to read input from a string instead of a file */
static int
myinput(char* buf, int max) {
       int len;
       if (parseCh == NULL)
             parseCh = parseString;
       len = strlen(parseCh);               /* remaining data available */
       /* Note: this code used to think that flex wants a null-terminated
        * string.  It does NOT, and returning 1 less character than it asks
        * for will cause failure under the right boundary conditions.  So
        * shut up and fill the buffer to the limit, you hear?
        */
       if (len > max)
             len = max;
       if (len > 0)
             memcpy(buf, parseCh, len);
       parseCh += len;
       return len; }
#endif /* FLEX_SCANNER */
