using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("Castle.Services.Transaction for Microsoft .NET Framework 2.0")]
[assembly: AssemblyDescriptionAttribute("Castle Transaction Services")]
[assembly: AssemblyCompanyAttribute("Castle Project")]
[assembly: AssemblyProductAttribute("Castle.Services.Transaction")]
[assembly: AssemblyCopyrightAttribute("Castle Project, original author or authors")]
[assembly: AssemblyVersionAttribute("1.0.3.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.3.4333")]
[assembly: AssemblyFileVersionAttribute("1.0.3.4333")]
[assembly: AssemblyDelaySignAttribute(false)]

