<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://webservices.sabre.com/sabreXML/2003/07" xmlns:tns="https://webservices.sabre.com/websvc" xmlns:eb="http://www.ebxml.org/namespaces/messageHeader" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" targetNamespace="https://webservices.sabre.com/websvc">
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://webservices.sabre.com/sabreXML/2003/07" schemaLocation="AddRemarkLLS1.1.1RQRS.xsd"/>
			<xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="msg-header-2_0.xsd"/>
			<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
			<xsd:import namespace="http://www.w3.org/1999/xlink" schemaLocation="xlink.xsd"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/soap/envelope/" schemaLocation="envelope.xsd"/>
			<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/ws/2002/12/secext" schemaLocation="wsse.xsd"/>
		</xsd:schema>
	</types>
	<message name="AddRemarkInput">
		<part name="header" element="eb:MessageHeader"/>
		<part name="header2" element="wsse:Security"/>
		<part name="body" element="xsd1:AddRemarkRQ"/>
	</message>
	<message name="AddRemarkOutput">
		<part name="header" element="eb:MessageHeader"/>
		<part name="header2" element="wsse:Security"/>
		<part name="body" element="xsd1:AddRemarkRS"/>
	</message>
	<portType name="AddRemarkPortType">
		<operation name="AddRemarkRQ">
			<input message="tns:AddRemarkInput"/>
			<output message="tns:AddRemarkOutput"/>
		</operation>
	</portType>
	<binding name="AddRemarkSoapBinding" type="tns:AddRemarkPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="AddRemarkRQ">
			<soap:operation soapAction="OTA"/>
			<input>
				<soap:header message="tns:AddRemarkInput" part="header" use="literal"/>
				<soap:header message="tns:AddRemarkInput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</input>
			<output>
				<soap:header message="tns:AddRemarkOutput" part="header" use="literal"/>
				<soap:header message="tns:AddRemarkOutput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="AddRemarkService">
		<port name="AddRemarkPortType" binding="tns:AddRemarkSoapBinding">
			<soap:address location="https://webservices.sabre.com/websvc"/>
		</port>
	</service>
</definitions>
