<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by Maciej (Sabre Deutschland Marketing GmbH) -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ota="http://www.opentravel.org/OTA/2003/05" xmlns:tns="https://webservices.sabre.com/websvc/lfs" xmlns:eb="http://www.ebxml.org/namespaces/messageHeader" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" targetNamespace="https://webservices.sabre.com/websvc/lfs">
	<types>
		<xs:schema>
			<xs:import schemaLocation="ebxml/msg-header-2_0.xsd" namespace="http://www.ebxml.org/namespaces/messageHeader"/>
			<xs:import schemaLocation="ebxml/wsse.xsd" namespace="http://schemas.xmlsoap.org/ws/2002/12/secext"/>
		</xs:schema>
		<xs:schema targetNamespace="http://www.opentravel.org/OTA/2003/05">
			<xs:include schemaLocation="ota/FS_OTA_AirLowFareSearchRQ.xsd"/>
			<xs:include schemaLocation="ota/FS_OTA_AirLowFareSearchRS1.xsd"/>
		</xs:schema>
	</types>
	<message name="OTA_AirLowFareSearchInput">
		<part name="ebHeader" element="eb:MessageHeader"/>
		<part name="wsseHeader" element="wsse:Security"/>
		<part name="bodyRQ" element="ota:OTA_AirLowFareSearchRQ"/>
	</message>
	<message name="OTA_AirLowFareSearchOutput">
		<part name="ebHeader" element="eb:MessageHeader"/>
		<part name="wsseHeader" element="wsse:Security"/>
		<part name="bodyRS" element="ota:OTA_AirLowFareSearchRS"/>
	</message>
	<portType name="OTA_AirLowFareSearchPortType">
		<operation name="OTA_AirLowFareSearchRQ">
			<input message="tns:OTA_AirLowFareSearchInput"/>
			<output message="tns:OTA_AirLowFareSearchOutput"/>
		</operation>
	</portType>
	<binding name="OTA_AirLowFareSearchBinding" type="tns:OTA_AirLowFareSearchPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="OTA_AirLowFareSearchRQ">
			<soap:operation soapAction="OTA_AirLowFareSearchRQ" style="document"/>
			<input>
				<soap:header message="tns:OTA_AirLowFareSearchInput" part="ebHeader" use="literal"/>
				<soap:header message="tns:OTA_AirLowFareSearchInput" part="wsseHeader" use="literal"/>
				<soap:body parts="bodyRQ" use="literal"/>
			</input>
			<output>
				<soap:header message="tns:OTA_AirLowFareSearchOutput" part="ebHeader" use="literal"/>
				<soap:header message="tns:OTA_AirLowFareSearchOutput" part="wsseHeader" use="literal"/>
				<soap:body parts="bodyRS" use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="OTA_AirLowFareSearchService">
		<port name="OTA_AirLowFareSearchPortType" binding="tns:OTA_AirLowFareSearchBinding">
			<soap:address location="https://webservices.sabre-merlin.de/XGateConnector/services/urn:XGate2"/>
		</port>
	</service>
</definitions>
